//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_request
    {
        public decimal auto_uid { get; set; }
        public string dba_name { get; set; }
        public string business_legal_name { get; set; }
        public string business_address { get; set; }
        public string business_address_add { get; set; }
        public string business_city { get; set; }
        public string business_state { get; set; }
        public string business_province { get; set; }
        public string business_zip { get; set; }
        public string business_country { get; set; }
        public string country_code { get; set; }
        public string business_phone { get; set; }
        public string business_fax { get; set; }
        public string business_url { get; set; }
        public string admin_pass { get; set; }
        public string admin_id { get; set; }
        public string owner_lname { get; set; }
        public string owner_fname { get; set; }
        public string owner_mail_address { get; set; }
        public string owner_mail_city { get; set; }
        public string owner_mail_state { get; set; }
        public string owner_mail_zip { get; set; }
        public string owner_mail_country { get; set; }
        public string owner_phone { get; set; }
        public string owner_email { get; set; }
        public string account_type { get; set; }
        public Nullable<decimal> payment_id { get; set; }
    }
}
