//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent
    {
        public decimal elt_account_number { get; set; }
        public string dba_name { get; set; }
        public string class_code { get; set; }
        public Nullable<System.DateTime> date_opened { get; set; }
        public string business_legal_name { get; set; }
        public string business_fed_taxid { get; set; }
        public string business_st_taxid { get; set; }
        public string usppi { get; set; }
        public string business_address { get; set; }
        public string business_address_add { get; set; }
        public string business_city { get; set; }
        public string business_province { get; set; }
        public string business_state { get; set; }
        public string business_zip { get; set; }
        public string business_country { get; set; }
        public string country_code { get; set; }
        public string business_phone { get; set; }
        public string business_fax { get; set; }
        public string business_url { get; set; }
        public string owner_ssn { get; set; }
        public string owner_lname { get; set; }
        public string owner_fname { get; set; }
        public string owner_mname { get; set; }
        public string owner_mail_address { get; set; }
        public string owner_mail_city { get; set; }
        public string owner_mail_state { get; set; }
        public string owner_mail_zip { get; set; }
        public string owner_mail_country { get; set; }
        public string owner_phone { get; set; }
        public string owner_email { get; set; }
        public string account_statue { get; set; }
        public string Agent_IATA_Code { get; set; }
        public string OTI_Code { get; set; }
        public string board_name { get; set; }
        public string iv_statement { get; set; }
        public string faa_approval_no { get; set; }
        public Nullable<decimal> maxuser { get; set; }
        public string is_dome { get; set; }
        public string is_intl { get; set; }
        public string faa_approval_date { get; set; }
        public string is_cartage { get; set; }
        public string is_warehouse { get; set; }
        public string is_accounting { get; set; }
        public string is_exporter { get; set; }
        public string is_aes { get; set; }
        public int ID { get; set; }
    }
}
