//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class all_currency_code
    {
        public decimal auto_uid { get; set; }
        public string country_name { get; set; }
        public string country_code { get; set; }
        public string currency_name { get; set; }
        public string currency_code { get; set; }
    }
}
