//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class all_accounts_journal
    {
        public decimal elt_account_number { get; set; }
        public decimal tran_seq_num { get; set; }
        public Nullable<decimal> gl_account_number { get; set; }
        public string gl_account_name { get; set; }
        public string tran_type { get; set; }
        public string tran_num { get; set; }
        public string air_ocean { get; set; }
        public Nullable<System.DateTime> tran_date { get; set; }
        public string customer_name { get; set; }
        public Nullable<decimal> customer_number { get; set; }
        public string memo { get; set; }
        public string split { get; set; }
        public Nullable<decimal> check_no { get; set; }
        public Nullable<decimal> debit_amount { get; set; }
        public Nullable<decimal> credit_amount { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<decimal> previous_balance { get; set; }
        public Nullable<decimal> gl_balance { get; set; }
        public Nullable<decimal> gl_previous_balance { get; set; }
        public Nullable<decimal> adjust_amount { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> debit_memo { get; set; }
        public Nullable<decimal> credit_memo { get; set; }
        public string flag_close { get; set; }
        public string print_check_as { get; set; }
        public string chk_complete { get; set; }
        public string chk_void { get; set; }
        public string is_org_merged { get; set; }
        public string is_recon_cleared { get; set; }
    }
}
