//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class application
    {
        public decimal app_num { get; set; }
        public Nullable<System.DateTime> date_applied { get; set; }
        public string dba_name { get; set; }
        public string business_legal_name { get; set; }
        public string business_fed_taxid { get; set; }
        public string business_st_taxid { get; set; }
        public string business_address { get; set; }
        public string business_city { get; set; }
        public string business_state { get; set; }
        public string business_zip { get; set; }
        public string business_country { get; set; }
        public string business_phone { get; set; }
        public string business_fax { get; set; }
        public string business_url { get; set; }
        public string owner_ssn { get; set; }
        public string owner_lname { get; set; }
        public string owner_fname { get; set; }
        public string owner_mname { get; set; }
        public string owner_mail_address { get; set; }
        public string owner_mail_city { get; set; }
        public string owner_mail_state { get; set; }
        public string owner_mail_zip { get; set; }
        public string owner_mail_country { get; set; }
        public string owner_phone { get; set; }
        public string owner_email { get; set; }
        public string attn_name { get; set; }
        public string notify_name { get; set; }
        public string admin_first_name { get; set; }
        public string admin_last_name { get; set; }
        public string admin_login { get; set; }
        public string admin_phone { get; set; }
        public string admin_email { get; set; }
        public string comment { get; set; }
        public string elt_comment { get; set; }
        public string staff_last_name { get; set; }
        public string staff_first_name { get; set; }
        public string app_status { get; set; }
        public Nullable<System.DateTime> last_process_date { get; set; }
    }
}
