//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_detail
    {
        public Nullable<decimal> elt_account_number { get; set; }
        public Nullable<decimal> invoice_no { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<decimal> bill_number { get; set; }
        public Nullable<decimal> vendor_number { get; set; }
        public string item_name { get; set; }
        public Nullable<int> item_no { get; set; }
        public Nullable<decimal> item_amt { get; set; }
        public Nullable<decimal> item_amt_origin { get; set; }
        public Nullable<decimal> item_expense_acct { get; set; }
        public Nullable<decimal> item_ap { get; set; }
        public Nullable<System.DateTime> tran_date { get; set; }
        public string @ref { get; set; }
        public string mb_no { get; set; }
        public string iType { get; set; }
        public string agent_debit_no { get; set; }
        public string is_org_merged { get; set; }
        public string is_manual { get; set; }
        public string hawb_master_hawb_num { get; set; }
        public string import_export { get; set; }
        public string hb_no { get; set; }
    }
}
