//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public decimal elt_account_number { get; set; }
        public decimal bill_number { get; set; }
        public string bill_type { get; set; }
        public Nullable<decimal> vendor_number { get; set; }
        public string vendor_name { get; set; }
        public Nullable<System.DateTime> bill_date { get; set; }
        public Nullable<System.DateTime> bill_due_date { get; set; }
        public Nullable<decimal> bill_amt { get; set; }
        public Nullable<decimal> bill_amt_paid { get; set; }
        public Nullable<decimal> bill_amt_due { get; set; }
        public string ref_no { get; set; }
        public Nullable<decimal> bill_expense_acct { get; set; }
        public Nullable<decimal> bill_ap { get; set; }
        public string bill_status { get; set; }
        public Nullable<decimal> print_id { get; set; }
        public string @lock { get; set; }
        public string pmt_method { get; set; }
        public string is_org_merged { get; set; }
    }
}
