//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking_confirm
    {
        public decimal auto_uid { get; set; }
        public string bc_no { get; set; }
        public Nullable<decimal> elt_account_number { get; set; }
        public Nullable<System.DateTime> document_date { get; set; }
        public string air_ocean { get; set; }
        public string booking_no { get; set; }
        public string master_no { get; set; }
        public string house_no { get; set; }
        public string sub_house_no { get; set; }
        public Nullable<decimal> shipper_acct { get; set; }
        public string shipper_name { get; set; }
        public string shipper_info { get; set; }
        public Nullable<decimal> deliver_to_acct { get; set; }
        public string deliver_to_name { get; set; }
        public string deliver_to_info { get; set; }
        public string cut_off_date { get; set; }
        public string export_reference { get; set; }
        public Nullable<decimal> carrier_acct { get; set; }
        public string carrier_name { get; set; }
        public string carrier_no { get; set; }
        public string place_of_receipt { get; set; }
        public string place_of_delivery { get; set; }
        public string dep_port { get; set; }
        public string arr_port { get; set; }
        public Nullable<System.DateTime> eta { get; set; }
        public Nullable<System.DateTime> etd { get; set; }
        public string move_type { get; set; }
        public Nullable<decimal> dest_agent_acct { get; set; }
        public string dest_agent_name { get; set; }
        public string dest_agent_info { get; set; }
        public Nullable<decimal> empty_container_pick_up_acct { get; set; }
        public string empty_container_pick_up_name { get; set; }
        public string empty_container_pick_up_info { get; set; }
        public string dangerous { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string quantity_unit { get; set; }
        public string item_desc { get; set; }
        public Nullable<decimal> gross_weight { get; set; }
        public string weight_scale { get; set; }
        public Nullable<decimal> dimension { get; set; }
        public string dimension_scale { get; set; }
        public string remark { get; set; }
    }
}
