//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrier_master
    {
        public decimal auto_uid { get; set; }
        public Nullable<decimal> elt_account_number { get; set; }
        public string carrier_name { get; set; }
        public string carrier_code_type { get; set; }
        public string carrier_code { get; set; }
        public string tran_type { get; set; }
        public Nullable<decimal> org_account_number { get; set; }
    }
}
