//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificate_origin_air_items
    {
        public decimal cert_id { get; set; }
        public string doc_num { get; set; }
        public string desc1 { get; set; }
        public string desc2 { get; set; }
        public string desc3 { get; set; }
        public Nullable<double> gross_weight { get; set; }
        public Nullable<double> measurement { get; set; }
        public string weight_scale { get; set; }
        public string measurement_scale { get; set; }
    }
}
