//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class charge_item
    {
        public decimal elt_account_number { get; set; }
        public int item_no { get; set; }
        public string item_name { get; set; }
        public string item_type { get; set; }
        public string item_desc { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> account_revenue { get; set; }
        public Nullable<decimal> account_expense { get; set; }
    }
}
