//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class check_queue
    {
        public decimal elt_account_number { get; set; }
        public decimal print_id { get; set; }
        public Nullable<decimal> check_no { get; set; }
        public string check_type { get; set; }
        public Nullable<decimal> check_amt { get; set; }
        public Nullable<decimal> vendor_number { get; set; }
        public string vendor_name { get; set; }
        public string vendor_info { get; set; }
        public Nullable<decimal> bank { get; set; }
        public Nullable<decimal> ap { get; set; }
        public string print_status { get; set; }
        public Nullable<System.DateTime> bill_date { get; set; }
        public Nullable<System.DateTime> bill_due_date { get; set; }
        public Nullable<System.DateTime> print_date { get; set; }
        public string memo { get; set; }
        public string pmt_method { get; set; }
        public string print_check_as { get; set; }
        public string is_org_merged { get; set; }
        public string chk_complete { get; set; }
        public string chk_void { get; set; }
    }
}
