//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class check_detail
    {
        public decimal elt_account_number { get; set; }
        public decimal print_id { get; set; }
        public int tran_id { get; set; }
        public Nullable<decimal> bill_number { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public string invoice_no { get; set; }
        public Nullable<decimal> bill_amt { get; set; }
        public Nullable<decimal> amt_due { get; set; }
        public Nullable<decimal> amt_paid { get; set; }
        public Nullable<decimal> amt_dispute { get; set; }
        public string memo { get; set; }
        public string pmt_method { get; set; }
    }
}
