//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_credits
    {
        public decimal elt_account_number { get; set; }
        public decimal customer_no { get; set; }
        public string customer_name { get; set; }
        public Nullable<decimal> credit { get; set; }
        public string is_org_merged { get; set; }
    }
}
