//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_payment
    {
        public decimal elt_account_number { get; set; }
        public Nullable<int> branch { get; set; }
        public decimal payment_no { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string ref_no { get; set; }
        public Nullable<decimal> customer_number { get; set; }
        public string customer_name { get; set; }
        public Nullable<decimal> third_party_number { get; set; }
        public string third_party_name { get; set; }
        public Nullable<decimal> accounts_receivable { get; set; }
        public Nullable<decimal> deposit_to { get; set; }
        public Nullable<decimal> received_amt { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string pmt_method { get; set; }
        public Nullable<decimal> existing_credits { get; set; }
        public Nullable<decimal> unapplied_amt { get; set; }
        public Nullable<decimal> added_amt { get; set; }
        public string is_org_merged { get; set; }
    }
}
