//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_credit_info
    {
        public decimal auto_uid { get; set; }
        public Nullable<decimal> elt_account_number { get; set; }
        public Nullable<decimal> customer_no { get; set; }
        public string memo { get; set; }
        public Nullable<decimal> credit { get; set; }
        public Nullable<System.DateTime> tran_date { get; set; }
        public string customer_name { get; set; }
        public Nullable<decimal> entry_no { get; set; }
        public Nullable<decimal> invoice_no { get; set; }
        public string ref_no { get; set; }
        public string is_refund { get; set; }
    }
}
