//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_payment_detail
    {
        public decimal elt_account_number { get; set; }
        public decimal payment_no { get; set; }
        public int item_id { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public string type { get; set; }
        public Nullable<decimal> invoice_no { get; set; }
        public Nullable<decimal> orig_amt { get; set; }
        public Nullable<decimal> amt_due { get; set; }
        public Nullable<decimal> payment { get; set; }
    }
}
