//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery_order
    {
        public decimal auto_uid { get; set; }
        public Nullable<decimal> elt_account_number { get; set; }
        public string mawb_no { get; set; }
        public string hawb_no { get; set; }
        public string sub_hawb_no { get; set; }
        public string shipper_name { get; set; }
        public string shipper_info { get; set; }
        public Nullable<decimal> shipper_acct { get; set; }
        public string consignee_name { get; set; }
        public string consignee_info { get; set; }
        public Nullable<decimal> consignee_acct { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string ref_no_Our { get; set; }
        public string carrier_name { get; set; }
        public string carrier_info { get; set; }
        public string cargo_location { get; set; }
        public string iType { get; set; }
        public string dep_port { get; set; }
        public string arr_port { get; set; }
        public Nullable<System.DateTime> eta { get; set; }
        public Nullable<System.DateTime> etd { get; set; }
        public Nullable<System.DateTime> free_date { get; set; }
        public string trucker_name { get; set; }
        public string trucker_info { get; set; }
        public string trucker_acct { get; set; }
        public string entry_billing_no { get; set; }
        public string customer_ref_no { get; set; }
        public string item_pieces { get; set; }
        public string item_desc { get; set; }
        public Nullable<double> item_gross_wt { get; set; }
        public string item_scale { get; set; }
        public Nullable<double> inland_charge { get; set; }
        public string inland_charge_type { get; set; }
        public string route { get; set; }
        public string sec_num { get; set; }
        public string handling { get; set; }
        public string attention { get; set; }
        public string employee { get; set; }
        public string anonymous { get; set; }
        public string file_name { get; set; }
        public string pickupfrom { get; set; }
        public string is_org_merged { get; set; }
        public string session_id { get; set; }
        public string Carrier_Code { get; set; }
        public Nullable<decimal> importer_acct { get; set; }
        public string importer_name { get; set; }
        public string importer_info { get; set; }
        public Nullable<decimal> pickup_acct { get; set; }
        public string pickup_name { get; set; }
        public string pickup_info { get; set; }
        public string dep_port_code { get; set; }
        public string arr_port_code { get; set; }
        public string delivery_ref_num { get; set; }
        public string dimension { get; set; }
        public string dimension_scale { get; set; }
    }
}
