//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELT_NOTIFICATION
    {
        public decimal elt_account_number { get; set; }
        public decimal userid { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> expired_to { get; set; }
    }
}
