//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class gl
    {
        public decimal elt_account_number { get; set; }
        public decimal gl_account_number { get; set; }
        public string gl_account_desc { get; set; }
        public string gl_master_type { get; set; }
        public string gl_account_type { get; set; }
        public Nullable<decimal> gl_account_balance { get; set; }
        public Nullable<decimal> gl_begin_balance { get; set; }
        public string gl_account_status { get; set; }
        public Nullable<System.DateTime> gl_account_cdate { get; set; }
        public Nullable<System.DateTime> gl_last_modified { get; set; }
        public Nullable<decimal> control_no { get; set; }
        public string gl_default { get; set; }
        public Nullable<decimal> gl_vendor_no { get; set; }
    }
}
