//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class gl_reference
    {
        public decimal gl_id { get; set; }
        public string gl_master_type { get; set; }
        public string gl_type { get; set; }
        public string remark { get; set; }
    }
}
