//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hawb_milestones
    {
        public decimal auto_uid { get; set; }
        public Nullable<decimal> elt_account_number { get; set; }
        public string hawb_num { get; set; }
        public string location_id { get; set; }
        public Nullable<decimal> seq_id { get; set; }
        public string job_type { get; set; }
        public string status { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
