//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hawb_Other_Charge
    {
        public decimal elt_account_number { get; set; }
        public string HAWB_NUM { get; set; }
        public int Tran_No { get; set; }
        public string Coll_Prepaid { get; set; }
        public string Carrier_Agent { get; set; }
        public Nullable<int> charge_code { get; set; }
        public string Charge_Desc { get; set; }
        public Nullable<decimal> Amt_HAWB { get; set; }
        public Nullable<decimal> Amt_Acct { get; set; }
        public Nullable<decimal> vendor_num { get; set; }
        public Nullable<int> cost_code { get; set; }
        public string cost_desc { get; set; }
        public Nullable<decimal> cost_amt { get; set; }
        public string invoice_only { get; set; }
    }
}
