//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAWB_master_drivers
    {
        public decimal auto_uid { get; set; }
        public string hawb_num { get; set; }
        public string mawb_num { get; set; }
        public Nullable<decimal> elt_account_number { get; set; }
        public Nullable<decimal> driver_acct { get; set; }
        public Nullable<decimal> piece { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> cost_item_no { get; set; }
        public Nullable<decimal> cost_amount { get; set; }
        public Nullable<decimal> cost_percent { get; set; }
        public string remark { get; set; }
        public Nullable<decimal> item_id { get; set; }
        public Nullable<decimal> driver_paid { get; set; }
    }
}
