//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAWB_master_add
    {
        public decimal auto_uid { get; set; }
        public string hawb_num { get; set; }
        public string mawb_num { get; set; }
        public string is_agent_house { get; set; }
        public Nullable<decimal> elt_account_number { get; set; }
        public Nullable<decimal> customer_acct { get; set; }
        public Nullable<decimal> billto_acct { get; set; }
        public string ship_status { get; set; }
        public string pickup_alert_date { get; set; }
        public string pickup_alert_time { get; set; }
        public string ready_date { get; set; }
        public string ready_time { get; set; }
        public string close_date { get; set; }
        public string close_time { get; set; }
        public string pickup_date { get; set; }
        public string pickup_time { get; set; }
        public string dispatch_date { get; set; }
        public string dispatch_time { get; set; }
        public string onboard_date { get; set; }
        public string onboard_time { get; set; }
        public string transfer_date { get; set; }
        public string transfer_time { get; set; }
        public string carrier_signer { get; set; }
        public string delivery_alert_date { get; set; }
        public string delivery_alert_time { get; set; }
        public string recover_date { get; set; }
        public string recover_time { get; set; }
        public string OFD_date { get; set; }
        public string OFD_time { get; set; }
        public string POD_date { get; set; }
        public string POD_time { get; set; }
        public string POD_signer { get; set; }
        public string ship_time_status { get; set; }
    }
}
