//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hbol_master
    {
        public decimal elt_account_number { get; set; }
        public string hbol_num { get; set; }
        public string booking_num { get; set; }
        public string mbol_num { get; set; }
        public string agent_name { get; set; }
        public string agent_info { get; set; }
        public Nullable<decimal> agent_no { get; set; }
        public string forward_agent_name { get; set; }
        public string forward_agent_info { get; set; }
        public Nullable<decimal> forward_agent_acct_num { get; set; }
        public string Shipper_Name { get; set; }
        public string Shipper_Info { get; set; }
        public Nullable<decimal> Shipper_acct_num { get; set; }
        public string Consignee_Name { get; set; }
        public string Consignee_Info { get; set; }
        public Nullable<decimal> Consignee_acct_num { get; set; }
        public string export_ref { get; set; }
        public string origin_country { get; set; }
        public string dest_country { get; set; }
        public string export_instr { get; set; }
        public string loading_pier { get; set; }
        public string move_type { get; set; }
        public string containerized { get; set; }
        public string pre_carriage { get; set; }
        public string pre_receipt_place { get; set; }
        public string export_carrier { get; set; }
        public string vessel_name { get; set; }
        public string loading_port { get; set; }
        public string unloading_port { get; set; }
        public Nullable<System.DateTime> departure_date { get; set; }
        public string delivery_place { get; set; }
        public string desc1 { get; set; }
        public string desc2 { get; set; }
        public string desc3 { get; set; }
        public string desc4 { get; set; }
        public string desc5 { get; set; }
        public string manifest_desc { get; set; }
        public string weight_cp { get; set; }
        public string prepaid_other_charge { get; set; }
        public string collect_other_charge { get; set; }
        public Nullable<int> pieces { get; set; }
        public string scale { get; set; }
        public Nullable<decimal> gross_weight { get; set; }
        public Nullable<decimal> measurement { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> height { get; set; }
        public string dem_detail { get; set; }
        public Nullable<double> charge_rate { get; set; }
        public Nullable<decimal> total_weight_charge { get; set; }
        public string Show_Prepaid_Weight_Charge { get; set; }
        public string Show_Collect_Weight_Charge { get; set; }
        public string Show_Prepaid_Other_Charge { get; set; }
        public string Show_Collect_Other_Charge { get; set; }
        public Nullable<decimal> declared_value { get; set; }
        public string tran_by { get; set; }
        public Nullable<System.DateTime> tran_date { get; set; }
        public string tran_place { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public string prepaid_invoiced { get; set; }
        public string collect_invoiced { get; set; }
        public string ci { get; set; }
        public string Notify_Name { get; set; }
        public string Notify_Info { get; set; }
        public Nullable<decimal> Notify_acct_num { get; set; }
        public string unit_qty { get; set; }
        public string SalesPerson { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> total_other_charge { get; set; }
        public Nullable<decimal> total_other_cost { get; set; }
        public string lc { get; set; }
        public string aes_xtn { get; set; }
        public string colo { get; set; }
        public Nullable<decimal> coloder_elt_acct { get; set; }
        public string colo_pay { get; set; }
        public string coloder_invoiced { get; set; }
        public string is_sub { get; set; }
        public string is_master { get; set; }
        public string sub_to_no { get; set; }
        public Nullable<int> sub_no { get; set; }
        public string is_master_closed { get; set; }
        public string is_invoice_queued { get; set; }
        public string is_org_merged { get; set; }
        public Nullable<decimal> master_weight_charge { get; set; }
        public Nullable<decimal> master_pieces { get; set; }
        public Nullable<decimal> master_gross_weight { get; set; }
        public Nullable<decimal> master_chargeable_weight { get; set; }
        public string dimtext { get; set; }
        public string sub_count { get; set; }
        public Nullable<decimal> of_cost { get; set; }
        public Nullable<decimal> agent_profit { get; set; }
        public Nullable<decimal> agent_profit_share { get; set; }
        public Nullable<decimal> other_agent_profit_carrier { get; set; }
        public Nullable<decimal> other_agent_profit_agent { get; set; }
        public string sed_stmt { get; set; }
    }
}
