//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ig_org_contact
    {
        public decimal elt_account_number { get; set; }
        public decimal org_account_number { get; set; }
        public int item_no { get; set; }
        public string name { get; set; }
        public string job_title { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string editedby { get; set; }
        public string cellPhone { get; set; }
        public string phoneExt { get; set; }
        public string is_org_merged { get; set; }
    }
}
