//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ig_ocean_ams_edi_header
    {
        public decimal elt_account_number { get; set; }
        public decimal doc_number { get; set; }
        public string v1_vessel_code { get; set; }
        public string v2_voyage_number { get; set; }
        public string v3_vessel_name { get; set; }
        public string v4_scac_code { get; set; }
        public string v5_vessel_flag { get; set; }
        public string v6_first_us_port_of_discharge { get; set; }
        public string v7_last_foreign_pol_s { get; set; }
        public string v7_last_foreign_pol { get; set; }
        public string p1_port_of_discharge { get; set; }
        public Nullable<System.DateTime> p2_estimated_date_of_arrival { get; set; }
        public string p3_terminal_operator_code_s { get; set; }
        public string p3_terminal_operator_code { get; set; }
        public string l1_port_of_load_s { get; set; }
        public string l1_port_of_load { get; set; }
        public Nullable<System.DateTime> l2_load_date { get; set; }
        public Nullable<System.DateTime> l3_load_time { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string b1_bill_of_lading_number { get; set; }
        public string b2_port_of_loading_s { get; set; }
        public string b2_port_of_loading { get; set; }
        public string b3_place_of_final_destination_s { get; set; }
        public string b3_place_of_final_destination { get; set; }
        public string b4_place_of_receipt { get; set; }
        public string b5_b_lading_status_code { get; set; }
        public string b6_b_lading_issuer_scac_code { get; set; }
        public string b7_snp1 { get; set; }
        public string b8_snp2 { get; set; }
        public string b9_manifested_units { get; set; }
        public string b10_total_gross_weight { get; set; }
        public string b11_booking_number { get; set; }
        public string b12_master_ocean_bill_number { get; set; }
        public string b13_agency_unique_code { get; set; }
        public string b14_snp3 { get; set; }
        public string b15_snp4 { get; set; }
        public string b16_snp5 { get; set; }
        public string b17_snp6 { get; set; }
        public string b18_snp7 { get; set; }
        public string b19_snp8 { get; set; }
        public string b20_weight_unit { get; set; }
        public string s1_shipper_name { get; set; }
        public string s2_shipper_address1 { get; set; }
        public string s3_shipper_address2 { get; set; }
        public string s4_shipper_city { get; set; }
        public string s5_shipper_state_province { get; set; }
        public string s6_shipper_postal_code { get; set; }
        public string s7_shipper_telephone_fax { get; set; }
        public string s8_shipper_iso_country_code { get; set; }
        public string s9_shipper_contact_name { get; set; }
        public string c1_consignee_name { get; set; }
        public string c2_consignee_address1 { get; set; }
        public string c3_consignee_address2 { get; set; }
        public string c4_consignee_city { get; set; }
        public string c5_consignee_state_province { get; set; }
        public string c6_consignee_postal_code { get; set; }
        public string c7_consignee_telephone_fax { get; set; }
        public string c8_consignee_iso_country_code { get; set; }
        public string c9_consignee_contact_name { get; set; }
        public string n1_notify_name { get; set; }
        public string n2_notify_address1 { get; set; }
        public string n3_notify_address2 { get; set; }
        public string n4_notify_city { get; set; }
        public string n5_notify_state_province { get; set; }
        public string n6_notify_postal_code { get; set; }
        public string n7_notify_telephone_fax { get; set; }
        public string n8_notify_iso_country_code { get; set; }
        public string n9_notify_party_contact_name { get; set; }
    }
}
