//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ig_ocean_ams_edi_item
    {
        public decimal elt_account_number { get; set; }
        public decimal doc_number { get; set; }
        public string i1_item_number { get; set; }
        public string i2_quantity { get; set; }
        public string i3_net_weight { get; set; }
        public string i4_volume { get; set; }
        public string i5_package_type { get; set; }
        public string i6_comodity_code { get; set; }
        public string i7_cash_value { get; set; }
        public string e1_equipment_number { get; set; }
        public string e2_seal_number1 { get; set; }
        public string e3_seal_number2 { get; set; }
        public string e4_length { get; set; }
        public string e5_width { get; set; }
        public string e6_height { get; set; }
        public string e7_iso_equipment { get; set; }
        public string e8_type_of_service { get; set; }
        public string e9_loaded_empty_total { get; set; }
        public string e10_equipment_desc_code { get; set; }
        public string d1_line_of_description { get; set; }
        public string m1_line_of_marks_and_numbers { get; set; }
        public string h1_hazard_code { get; set; }
        public string h2_hazard_class { get; set; }
        public string h3_hazard_description { get; set; }
        public string h4_hazard_contact { get; set; }
        public string h5_un_page_number { get; set; }
        public string h6_flashpoint_temperature { get; set; }
        public string h7_hazard_code_qualifier { get; set; }
        public string h8_hazard_unit_of_measure { get; set; }
        public string h9_negative_indigator { get; set; }
        public string h10_hazard_label { get; set; }
        public string h11_hazard_classification { get; set; }
    }
}
