//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ig_schedule_b
    {
        public decimal elt_account_number { get; set; }
        public decimal org_account_number { get; set; }
        public string sb { get; set; }
        public string sb_unit1 { get; set; }
        public string sb_unit2 { get; set; }
        public string description { get; set; }
        public string is_org_merged { get; set; }
        public string export_code { get; set; }
        public string license_type { get; set; }
        public string eccn { get; set; }
        public Nullable<decimal> sb_id { get; set; }
    }
}
