//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ihawb_weight_charge
    {
        public decimal elt_account_number { get; set; }
        public string HAWB_NUM { get; set; }
        public int Tran_No { get; set; }
        public Nullable<int> No_Pieces { get; set; }
        public Nullable<decimal> Gross_Weight { get; set; }
        public Nullable<decimal> Adjusted_Weight { get; set; }
        public string Kg_Lb { get; set; }
        public string Service_Code { get; set; }
        public string Rate_Class { get; set; }
        public string Commodity_Item_No { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> Dimension { get; set; }
        public string Dem_Detail { get; set; }
        public Nullable<decimal> Chargeable_Weight { get; set; }
        public Nullable<decimal> Rate_Charge { get; set; }
        public Nullable<decimal> Total_Charge { get; set; }
        public string Desc1 { get; set; }
        public string Desc2 { get; set; }
    }
}
