//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class import_hawb
    {
        public decimal elt_account_number { get; set; }
        public Nullable<decimal> agent_elt_acct { get; set; }
        public Nullable<decimal> agent_org_acct { get; set; }
        public Nullable<System.DateTime> tran_dt { get; set; }
        public string iType { get; set; }
        public string mawb_num { get; set; }
        public string hawb_num { get; set; }
        public int sec { get; set; }
        public Nullable<decimal> invoice_no { get; set; }
        public Nullable<System.DateTime> process_dt { get; set; }
        public string processed { get; set; }
        public string shipper_name { get; set; }
        public string shipper_info { get; set; }
        public Nullable<decimal> shipper_acct { get; set; }
        public string consignee_name { get; set; }
        public string consignee_info { get; set; }
        public Nullable<decimal> consignee_acct { get; set; }
        public string notify_name { get; set; }
        public string notify_info { get; set; }
        public Nullable<decimal> notify_acct { get; set; }
        public string broker_info { get; set; }
        public Nullable<decimal> broker_acct { get; set; }
        public Nullable<decimal> pieces { get; set; }
        public string uom { get; set; }
        public Nullable<decimal> gross_wt { get; set; }
        public string scale1 { get; set; }
        public Nullable<decimal> chg_wt { get; set; }
        public string scale2 { get; set; }
        public string prepaid_collect { get; set; }
        public Nullable<decimal> freight_collect { get; set; }
        public Nullable<decimal> oc_collect { get; set; }
        public string prepared_by { get; set; }
        public string sub_mawb1 { get; set; }
        public string sub_mawb2 { get; set; }
        public string customer_ref { get; set; }
        public string delivery_place { get; set; }
        public string etd2 { get; set; }
        public string eta2 { get; set; }
        public string container_location { get; set; }
        public string destination { get; set; }
        public string free_date { get; set; }
        public string go_date { get; set; }
        public string it_number { get; set; }
        public string it_date { get; set; }
        public string it_entry_port { get; set; }
        public string cargo_location { get; set; }
        public string desc1 { get; set; }
        public string desc2 { get; set; }
        public string desc3 { get; set; }
        public string desc4 { get; set; }
        public string desc5 { get; set; }
        public string remarks { get; set; }
        public Nullable<int> term { get; set; }
        public Nullable<System.DateTime> pickup_date { get; set; }
        public string igSub_HAWB { get; set; }
        public string SalesPerson { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> fc_rate { get; set; }
        public Nullable<decimal> fc_charge { get; set; }
        public Nullable<decimal> total_other_charge { get; set; }
        public string dep_code { get; set; }
        public string arr_code { get; set; }
        public string is_default_rate { get; set; }
        public string eta { get; set; }
        public string etd { get; set; }
        public string flt_no { get; set; }
        public string broker_name { get; set; }
        public string is_org_merged { get; set; }
        public string dep_port { get; set; }
        public string arr_port { get; set; }
        public string carrier_code { get; set; }
    }
}
