//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class import_mawb
    {
        public decimal elt_account_number { get; set; }
        public Nullable<decimal> agent_elt_acct { get; set; }
        public string export_agent_name { get; set; }
        public Nullable<decimal> agent_org_acct { get; set; }
        public Nullable<System.DateTime> tran_dt { get; set; }
        public string iType { get; set; }
        public string mawb_num { get; set; }
        public int sec { get; set; }
        public string sub_mawb { get; set; }
        public Nullable<System.DateTime> process_dt { get; set; }
        public string processed { get; set; }
        public string carrier { get; set; }
        public string vessel_name { get; set; }
        public string file_no { get; set; }
        public string voyage_no { get; set; }
        public string flt_no { get; set; }
        public string etd { get; set; }
        public string eta { get; set; }
        public string dep_port { get; set; }
        public string arr_port { get; set; }
        public string cargo_location { get; set; }
        public Nullable<System.DateTime> last_free_date { get; set; }
        public string pieces { get; set; }
        public string scale1 { get; set; }
        public string gross_wt { get; set; }
        public string scale2 { get; set; }
        public string chg_wt { get; set; }
        public string scale3 { get; set; }
        public string agent_debit_no { get; set; }
        public Nullable<decimal> agent_debit_amt { get; set; }
        public string it_number { get; set; }
        public string it_date { get; set; }
        public string it_entry_port { get; set; }
        public string place_of_delivery { get; set; }
        public string SalesPerson { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string dep_code { get; set; }
        public string arr_code { get; set; }
        public string carrier_code { get; set; }
        public string is_org_merged { get; set; }
    }
}
