//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_queue
    {
        public decimal elt_account_number { get; set; }
        public decimal queue_id { get; set; }
        public System.DateTime inqueue_date { get; set; }
        public Nullable<System.DateTime> outqueue_date { get; set; }
        public string agent_shipper { get; set; }
        public string hawb_num { get; set; }
        public string mawb_num { get; set; }
        public string bill_to { get; set; }
        public Nullable<decimal> bill_to_org_acct { get; set; }
        public string agent_name { get; set; }
        public Nullable<decimal> agent_org_acct { get; set; }
        public string master_agent { get; set; }
        public string air_ocean { get; set; }
        public string master_only { get; set; }
        public string invoiced { get; set; }
        public string is_dome { get; set; }
    }
}
