//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAWB_NUMBER
    {
        public decimal elt_account_number { get; set; }
        public string mawb_no { get; set; }
        public string Carrier_Code { get; set; }
        public string Carrier_MC_ICC { get; set; }
        public Nullable<decimal> Carrier_acct { get; set; }
        public string Carrier_Desc { get; set; }
        public string scac { get; set; }
        public string Flight_ { get; set; }
        public string File_ { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Origin_Port_ID { get; set; }
        public Nullable<decimal> origin_port_aes_code { get; set; }
        public string Origin_Port_Location { get; set; }
        public string Origin_Port_State { get; set; }
        public string Origin_Port_Country { get; set; }
        public string Dest_Port_ID { get; set; }
        public Nullable<decimal> dest_port_aes_code { get; set; }
        public string Dest_Port_Location { get; set; }
        public string Dest_Port_Country { get; set; }
        public string dest_country_code { get; set; }
        public string To { get; set; }
        public string By { get; set; }
        public string To_1 { get; set; }
        public string By_1 { get; set; }
        public string To_2 { get; set; }
        public string By_2 { get; set; }
        public string Flight_1 { get; set; }
        public string Flight_2 { get; set; }
        public Nullable<System.DateTime> ETD_DATE1 { get; set; }
        public Nullable<System.DateTime> ETD_DATE2 { get; set; }
        public Nullable<System.DateTime> ETA_DATE1 { get; set; }
        public Nullable<System.DateTime> ETA_DATE2 { get; set; }
        public Nullable<decimal> Weight_Reserved { get; set; }
        public string Weight_Scale { get; set; }
        public string airline_staff { get; set; }
        public string Status { get; set; }
        public string used { get; set; }
        public string is_dome { get; set; }
        public Nullable<decimal> pieces { get; set; }
        public string master_type { get; set; }
        public string service_level { get; set; }
        public string service_level_other { get; set; }
        public Nullable<System.DateTime> booking_date { get; set; }
        public string is_inbound { get; set; }
        public Nullable<decimal> inbound_customer_acct { get; set; }
    }
}
