//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAWB_MASTER
    {
        public decimal elt_account_number { get; set; }
        public string MAWB_NUM { get; set; }
        public string DEP_AIRPORT_CODE { get; set; }
        public Nullable<decimal> master_agent { get; set; }
        public Nullable<decimal> airline_vendor_num { get; set; }
        public string Shipper_Name { get; set; }
        public string Shipper_Info { get; set; }
        public string Shipper_account_number { get; set; }
        public string ff_shipper_acct { get; set; }
        public string Consignee_Name { get; set; }
        public string Consignee_Info { get; set; }
        public string Consignee_acct_num { get; set; }
        public string ff_consignee_acct { get; set; }
        public string Issue_Carrier_agent { get; set; }
        public string Agent_IATA_Code { get; set; }
        public string Account_No { get; set; }
        public string Departure_Airport { get; set; }
        public string IssuedBy { get; set; }
        public string Account_Info { get; set; }
        public string to_1 { get; set; }
        public string by_1 { get; set; }
        public string to_2 { get; set; }
        public string by_2 { get; set; }
        public string to_3 { get; set; }
        public string by_3 { get; set; }
        public string Currency { get; set; }
        public string Charge_Code { get; set; }
        public string PPO_1 { get; set; }
        public string COLL_1 { get; set; }
        public string PPO_2 { get; set; }
        public string COLL_2 { get; set; }
        public string Declared_Value_Carriage { get; set; }
        public string Declared_Value_Customs { get; set; }
        public string Dest_Airport { get; set; }
        public string Flight_Date_1 { get; set; }
        public string Flight_Date_2 { get; set; }
        public string Insurance_AMT { get; set; }
        public string Handling_Info { get; set; }
        public string dest_country { get; set; }
        public string SCI { get; set; }
        public Nullable<decimal> Total_Pieces { get; set; }
        public Nullable<decimal> Adjusted_Weight { get; set; }
        public Nullable<decimal> Total_Gross_Weight { get; set; }
        public Nullable<decimal> total_chargeable_weight { get; set; }
        public string Weight_Scale { get; set; }
        public Nullable<decimal> Total_Weight_Charge_HAWB { get; set; }
        public Nullable<decimal> Total_Weight_Charge_ACCT { get; set; }
        public Nullable<decimal> Total_Other_Charges { get; set; }
        public Nullable<decimal> total_other_cost { get; set; }
        public Nullable<decimal> Prepaid_Weight_Charge { get; set; }
        public Nullable<decimal> Collect_Weight_Charge { get; set; }
        public Nullable<decimal> Prepaid_Valuation_Charge { get; set; }
        public Nullable<decimal> Collect_Valuation_Charge { get; set; }
        public Nullable<decimal> Prepaid_Tax { get; set; }
        public Nullable<decimal> Collect_Tax { get; set; }
        public Nullable<decimal> Prepaid_Due_Agent { get; set; }
        public Nullable<decimal> Collect_Due_Agent { get; set; }
        public Nullable<decimal> Prepaid_Due_Carrier { get; set; }
        public Nullable<decimal> Collect_Due_Carrier { get; set; }
        public Nullable<decimal> Prepaid_Unused { get; set; }
        public Nullable<decimal> Collect_Unused { get; set; }
        public Nullable<decimal> Prepaid_Total { get; set; }
        public Nullable<decimal> Collect_Total { get; set; }
        public string Signature { get; set; }
        public Nullable<System.DateTime> Date_Executed { get; set; }
        public string Place_Executed { get; set; }
        public string Execution { get; set; }
        public Nullable<System.DateTime> Date_Last_Modified { get; set; }
        public Nullable<decimal> Currency_Conv_Rate { get; set; }
        public Nullable<decimal> CC_Charge_Dest_Rate { get; set; }
        public Nullable<decimal> Charge_at_Dest { get; set; }
        public Nullable<decimal> Total_Collect_Charge { get; set; }
        public string Desc1 { get; set; }
        public string Desc2 { get; set; }
        public string Show_Weight_Charge_Shipper { get; set; }
        public string Show_Weight_Charge_Consignee { get; set; }
        public string Show_Prepaid_Other_Charge_Shipper { get; set; }
        public string Show_Collect_Other_Charge_Shipper { get; set; }
        public string Show_Prepaid_Other_Charge_Consignee { get; set; }
        public string Show_Collect_Other_Charge_Consignee { get; set; }
        public string Invoiced { get; set; }
        public string Notify_no { get; set; }
        public string SalesPerson { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string is_org_merged { get; set; }
        public string dimtext { get; set; }
        public string reference_number { get; set; }
        public string is_dome { get; set; }
        public string master_type { get; set; }
        public string bill_to_party { get; set; }
        public string service_level_other { get; set; }
        public string iac_num { get; set; }
        public string known_shipper { get; set; }
        public string unknown_shipper { get; set; }
        public string item_under_16 { get; set; }
        public string shipper_reference_num { get; set; }
        public string carrier_icc_num { get; set; }
        public string dim_text { get; set; }
        public Nullable<decimal> shipper_COD { get; set; }
        public string third_party_no { get; set; }
        public string is_inbound { get; set; }
        public string service_level { get; set; }
        public Nullable<decimal> cod_amount { get; set; }
        public Nullable<decimal> pickup_charge { get; set; }
        public Nullable<decimal> origin_adv_charge { get; set; }
        public string origin_adv_charge_desc { get; set; }
        public Nullable<decimal> dest_adv_charge { get; set; }
        public string dest_adv_charge_desc { get; set; }
        public Nullable<decimal> item_prepaid { get; set; }
        public Nullable<decimal> item_collect { get; set; }
        public Nullable<decimal> cod_fee { get; set; }
        public Nullable<decimal> other_charge { get; set; }
        public Nullable<decimal> delivery_charge { get; set; }
        public Nullable<decimal> Total_Freight_Cost { get; set; }
        public string aes_xtn { get; set; }
        public string sed_stmt { get; set; }
    }
}
