//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mbol_other_cost
    {
        public decimal auto_uid { get; set; }
        public Nullable<decimal> elt_account_number { get; set; }
        public string booking_num { get; set; }
        public Nullable<decimal> vendor_no { get; set; }
        public Nullable<decimal> cost_amt { get; set; }
        public Nullable<decimal> item_no { get; set; }
        public string cost_desc { get; set; }
    }
}
