//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class page_user_access
    {
        public decimal elt_account_number { get; set; }
        public decimal user_id { get; set; }
        public int page_id { get; set; }
        public bool is_bloked { get; set; }
    }
}
