//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_due
    {
        public decimal auto_uid { get; set; }
        public Nullable<decimal> elt_account_number { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<decimal> pmt_amount { get; set; }
        public string pmt_desc { get; set; }
        public string pmt_status { get; set; }
        public string tran_id { get; set; }
        public Nullable<decimal> resp_code { get; set; }
        public Nullable<decimal> resp_res_code { get; set; }
        public string resp_res_text { get; set; }
        public string auth_code { get; set; }
        public string avs_code { get; set; }
        public Nullable<System.DateTime> auth_date { get; set; }
    }
}
