//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pickup_order
    {
        public decimal auto_uid { get; set; }
        public Nullable<decimal> elt_account_number { get; set; }
        public string Booking_NUM { get; set; }
        public string MAWB_NUM { get; set; }
        public string HAWB_NUM { get; set; }
        public string sub_hawb_no { get; set; }
        public string Shipper_Name { get; set; }
        public string Shipper_Info { get; set; }
        public Nullable<decimal> Shipper_account_number { get; set; }
        public string Pickup_Name { get; set; }
        public string Pickup_Info { get; set; }
        public Nullable<decimal> Pickup_account_number { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ref_no_Our { get; set; }
        public string Carrier_Name { get; set; }
        public string Carrier_Info { get; set; }
        public Nullable<decimal> Carrier_account_number { get; set; }
        public string Carrier_Code { get; set; }
        public string eType { get; set; }
        public string Origin_Port_Code { get; set; }
        public string Origin_Port_Location { get; set; }
        public string Dest_Port_Code { get; set; }
        public string Dest_Port_Location { get; set; }
        public Nullable<System.DateTime> ETA_DATE1 { get; set; }
        public Nullable<System.DateTime> ETD_DATE1 { get; set; }
        public Nullable<System.DateTime> free_date { get; set; }
        public string trucker_name { get; set; }
        public string trucker_acct { get; set; }
        public string entry_billing_no { get; set; }
        public string customer_ref_no { get; set; }
        public string Total_Pieces { get; set; }
        public string Desc2 { get; set; }
        public Nullable<double> Total_Gross_Weight { get; set; }
        public string Weight_Scale { get; set; }
        public Nullable<double> inland_charge { get; set; }
        public string inland_charge_type { get; set; }
        public string route { get; set; }
        public string sec_num { get; set; }
        public string Handling_Info { get; set; }
        public string attention { get; set; }
        public string contact { get; set; }
        public string employee { get; set; }
        public string anonymous { get; set; }
        public string file_name { get; set; }
        public string session_id { get; set; }
        public string is_org_merged { get; set; }
        public string dimension { get; set; }
        public string dimension_scale { get; set; }
        public string pickup_ref_num { get; set; }
        public string po_num { get; set; }
        public string file_type { get; set; }
        public string is_hazard { get; set; }
    }
}
