//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class port
    {
        public decimal elt_account_number { get; set; }
        public string port_code { get; set; }
        public string port_desc { get; set; }
        public string port_id { get; set; }
        public string port_city { get; set; }
        public string port_state { get; set; }
        public string port_country { get; set; }
        public string port_country_code { get; set; }
    }
}
