//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateEntryRow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RateEntryRow()
        {
            this.RateBlockDefinitions = new HashSet<RateBlockDefinition>();
        }
    
        public int RouteID { get; set; }
        public int ID { get; set; }
        public int CarrierCode { get; set; }
        public Nullable<double> Share { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RateBlockDefinition> RateBlockDefinitions { get; set; }
        public virtual RateRoute RateRoute { get; set; }
    }
}
