//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RateRoute()
        {
            this.RateEntryRows = new HashSet<RateEntryRow>();
        }
    
        public int ID { get; set; }
        public string Origin { get; set; }
        public string Dest { get; set; }
        public string Unit { get; set; }
        public string UnitText { get; set; }
        public string CustomerOrgName { get; set; }
        public Nullable<int> customer_org_account_number { get; set; }
        public string AgentOrgName { get; set; }
        public Nullable<int> agent_org_account_number { get; set; }
        public int elt_account_number { get; set; }
        public int RateType { get; set; }
        public string Share { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RateEntryRow> RateEntryRows { get; set; }
    }
}
