//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recent_Work
    {
        public decimal workid { get; set; }
        public Nullable<decimal> elt_account_number { get; set; }
        public string user_id { get; set; }
        public string workdate { get; set; }
        public string docnum { get; set; }
        public string title { get; set; }
        public string surl { get; set; }
        public string workdetail { get; set; }
        public string remark { get; set; }
        public string status { get; set; }
    }
}
