//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class reconcile
    {
        public decimal recon_id { get; set; }
        public Nullable<decimal> elt_account_number { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string recon_state { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> statement_ending_date { get; set; }
        public Nullable<double> opening_balance { get; set; }
        public Nullable<double> statement_ending_balance { get; set; }
        public Nullable<double> total_cleared { get; set; }
        public Nullable<double> total_uncleared { get; set; }
        public Nullable<double> system_balance_asof_statement { get; set; }
        public Nullable<double> system_balance_asof_recon_date { get; set; }
        public Nullable<double> total_unclear_after_statement { get; set; }
        public Nullable<System.DateTime> service_charge_date { get; set; }
        public Nullable<System.DateTime> interested_earned_date { get; set; }
        public Nullable<double> service_charge { get; set; }
        public Nullable<double> interest_earned { get; set; }
        public decimal bank_account_number { get; set; }
        public Nullable<System.DateTime> recon_beginning_date { get; set; }
        public Nullable<decimal> gj_entry_no { get; set; }
    }
}
