//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SE_Pages
    {
        public int Page_Id { get; set; }
        public Nullable<int> Module_Id { get; set; }
        public string Name { get; set; }
        public string Extention { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string PhysicalPage { get; set; }
        public string Deleted { get; set; }
        public Nullable<int> morder { get; set; }
    }
}
