//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SE_User_Authority
    {
        public decimal elt_account_number { get; set; }
        public decimal UserID { get; set; }
        public int Page_Id { get; set; }
        public int Authority_Id { get; set; }
        public string Fav { get; set; }
    }
}
