//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class sed_detail
    {
        public decimal elt_account_number { get; set; }
        public string hawb_num { get; set; }
        public int item_no { get; set; }
        public string dfm { get; set; }
        public string b_number { get; set; }
        public string item_desc { get; set; }
        public Nullable<int> b_qty1 { get; set; }
        public string unit1 { get; set; }
        public Nullable<int> b_qty2 { get; set; }
        public string unit2 { get; set; }
        public Nullable<decimal> gross_weight { get; set; }
        public string vin { get; set; }
        public Nullable<decimal> item_value { get; set; }
        public string export_code { get; set; }
        public string license_type { get; set; }
        public string mawb_num { get; set; }
        public Nullable<decimal> sed_id { get; set; }
        public string eccn { get; set; }
        public string license_number { get; set; }
    }
}
