//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class setup_master
    {
        public decimal page_id { get; set; }
        public Nullable<decimal> seq_id { get; set; }
        public string title { get; set; }
        public string setup_type { get; set; }
        public string setup_url { get; set; }
        public string valid_url { get; set; }
        public string remark { get; set; }
    }
}
