//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionDefinition
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Descripton { get; set; }
        public Nullable<bool> is_product { get; set; }
    }
}
