//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_master
    {
        public Nullable<decimal> elt_account_number { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public string page_label { get; set; }
        public string page_url { get; set; }
        public string top_module { get; set; }
        public string sub_module { get; set; }
        public string page_status { get; set; }
        public string access_level { get; set; }
        public Nullable<decimal> page_seq_id { get; set; }
        public Nullable<decimal> sub_seq_id { get; set; }
        public Nullable<decimal> top_seq_id { get; set; }
        public decimal page_id { get; set; }
        public Nullable<bool> is_obsolete { get; set; }
        public string master_url { get; set; }
    }
}
