//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_org
    {
        public Nullable<decimal> elt_account_number { get; set; }
        public decimal org_account_number { get; set; }
        public string dba_name { get; set; }
        public string class_code { get; set; }
        public string isFrequently { get; set; }
        public string business_address { get; set; }
        public string business_address2 { get; set; }
        public string business_city { get; set; }
        public string business_state { get; set; }
        public string business_zip { get; set; }
        public string business_country { get; set; }
        public string b_country_code { get; set; }
        public string owner_fname { get; set; }
        public string owner_title { get; set; }
        public string business_phone { get; set; }
        public string business_fax { get; set; }
        public string business_url { get; set; }
        public string owner_email { get; set; }
        public string c2FirstName { get; set; }
        public string c2Phone { get; set; }
        public string c2Fax { get; set; }
        public string c2Email { get; set; }
        public string business_fed_taxid { get; set; }
        public string comment { get; set; }
        public string comment2 { get; set; }
        public string is_shipper { get; set; }
        public string is_agent { get; set; }
        public string is_consignee { get; set; }
        public string z_is_trucker { get; set; }
        public string z_is_special { get; set; }
        public string owner_mail_address { get; set; }
        public string refferedBy { get; set; }
        public Nullable<System.DateTime> date_opened { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
    }
}
