//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class USCounty
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string StateAbbreviation { get; set; }
        public string StateName { get; set; }
    }
}
