//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_files
    {
        public decimal elt_account_number { get; set; }
        public decimal org_no { get; set; }
        public string file_name { get; set; }
        public Nullable<decimal> file_size { get; set; }
        public string file_type { get; set; }
        public byte[] file_content { get; set; }
        public string file_checked { get; set; }
        public Nullable<System.DateTime> in_dt { get; set; }
    }
}
