//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_pay_bill
    {
        public Nullable<decimal> bill_number { get; set; }
        public decimal print_id { get; set; }
        public decimal elt_account_number { get; set; }
        public Nullable<decimal> vendor_number { get; set; }
        public string vendor_name { get; set; }
        public Nullable<System.DateTime> bill_date { get; set; }
        public Nullable<System.DateTime> bill_due_date { get; set; }
        public Nullable<System.DateTime> print_date { get; set; }
        public string chk_void { get; set; }
        public string chk_complete { get; set; }
        public Nullable<decimal> amt_due { get; set; }
        public Nullable<decimal> amt_paid { get; set; }
    }
}
