//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ArrivalNotice
    {
        public decimal invoice_no { get; set; }
        public string Customer_Number { get; set; }
        public decimal elt_account_number { get; set; }
        public string mawb_num { get; set; }
        public string hawb_num { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public string air_ocean { get; set; }
        public string import_export { get; set; }
        public string Origin { get; set; }
        public string Dest { get; set; }
    }
}
