//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_mawb_booking_info
    {
        public string mServiceLevel { get; set; }
        public string mawb_no { get; set; }
        public string vDepCode { get; set; }
        public string vArrCode { get; set; }
        public string mDepartureAirportCode { get; set; }
        public string mDepartureAirport { get; set; }
        public string mDepartureState { get; set; }
        public string mTo { get; set; }
        public string mBy { get; set; }
        public string mTo1 { get; set; }
        public string mBy1 { get; set; }
        public string mTo2 { get; set; }
        public string mBy2 { get; set; }
        public string mDestAirport { get; set; }
        public string mDestCountry { get; set; }
        public string mFlight1 { get; set; }
        public string mFlight2 { get; set; }
        public Nullable<System.DateTime> mETDDate1 { get; set; }
        public Nullable<System.DateTime> mExportDate { get; set; }
        public Nullable<System.DateTime> mETDDate2 { get; set; }
        public string mCarrierDesc { get; set; }
        public string mFile { get; set; }
        public decimal mOrgNum { get; set; }
        public string mFlightDate1 { get; set; }
        public string mFlightDate2 { get; set; }
        public decimal elt_account_number { get; set; }
    }
}
