//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELT.Shared.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse_history
    {
        public decimal auto_uid { get; set; }
        public string wr_num { get; set; }
        public string so_num { get; set; }
        public Nullable<decimal> elt_account_number { get; set; }
        public string history_type { get; set; }
        public Nullable<System.DateTime> history_date { get; set; }
        public Nullable<decimal> item_piece_remain { get; set; }
        public Nullable<decimal> item_piece_origin { get; set; }
        public Nullable<decimal> item_piece_shipout { get; set; }
    }
}
