vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|20 Sep 2006 22:28:48 -0000
vti_extenderversion:SR|5.0.2.6790
vti_cacheddtm:TX|21 Sep 2006 16:11:00 -0000
vti_filesize:IR|15548
vti_cachedtitle:SR|FreightEasy-A complete Freight Forwarding System Made Easy
vti_cachedbodystyle:SR|<body onLoad="MM_preloadImages('images/button_elthome_over.gif','images/button_morenews_over.gif','images/button_login_help_over.gif','images/link_readmore_over.gif')">
vti_cachedlinkinfo:VX|Q|css/style_freighteasy.css H|images/favicon.ico S|../freighteasy/images/background_whole.gif S|images/background_body.gif H|../index.aspx H|index.aspx S|images/freighteasy_logo.gif S|images/spacer.gif S|images/question.gif S|images/spacer.gif S|images/index_intro.jpg S|images/feature_default.gif K|freighteasy.aspx S|images/link_readmore.gif S|images/feature_question.gif S|images/member_login.gif S|images/industry_news.gif S|../images/spacer.gif S|<%\\ Request.ServerVariables["SERVER_NAME"].ToLower();\\ %>/IFF_MAIN/Authentication/login2.aspx H|getting_tips.asp S|images/button_login_help.gif H|javascript:; H|http://www.cbp.gov/xp/cgov/newsroom S|images/button_morenews.gif S|images/back_sidetab.gif S|images/icon_pro_home.gif H|introduction.asp H|why_fe.asp H|features.asp H|faqs.asp S|images/icon_links.gif H|account_setup.asp H|getting_tips.asp H|../support.asp S|images/spacer.gif H|../index.aspx S|images/footer_home.gif S|images/footer_middle.gif H|../legal.asp S|images/footer_legal.gif S|images/footer_middle.gif H|../contact.asp S|images/footer_contact.gif S|images/spacer.gif S|images/footer.gif S|images/spacer.gif
vti_cachedsvcrellinks:VX|FQUS|freighteasy/css/style_freighteasy.css NHUS|freighteasy/images/favicon.ico FSUS|freighteasy/images/background_whole.gif FSUS|freighteasy/images/background_body.gif FHUS|index.aspx FHUS|freighteasy/index.aspx FSUS|freighteasy/images/freighteasy_logo.gif FSUS|freighteasy/images/spacer.gif FSUS|freighteasy/images/question.gif FSUS|freighteasy/images/spacer.gif NSUS|freighteasy/images/index_intro.jpg NSUS|freighteasy/images/feature_default.gif FKUS|freighteasy/freighteasy.aspx NSUS|freighteasy/images/link_readmore.gif NSUS|freighteasy/images/feature_question.gif FSUS|freighteasy/images/member_login.gif FSUS|freighteasy/images/industry_news.gif FSUS|images/spacer.gif USUS|<%\\ Request.ServerVariables["SERVER_NAME"].ToLower();\\ %>/IFF_MAIN/Authentication/login2.aspx FHUS|freighteasy/getting_tips.asp NSUS|freighteasy/images/button_login_help.gif SHUS|javascript:; NHHS|http://www.cbp.gov/xp/cgov/newsroom FSUS|freighteasy/images/button_morenews.gif FSUS|freighteasy/images/back_sidetab.gif FSUS|freighteasy/images/icon_pro_home.gif FHUS|freighteasy/introduction.asp FHUS|freighteasy/why_fe.asp FHUS|freighteasy/features.asp FHUS|freighteasy/faqs.asp FSUS|freighteasy/images/icon_links.gif FHUS|freighteasy/account_setup.asp FHUS|freighteasy/getting_tips.asp FHUS|support.asp FSUS|freighteasy/images/spacer.gif FHUS|index.aspx FSUS|freighteasy/images/footer_home.gif FSUS|freighteasy/images/footer_middle.gif NHUS|legal.asp FSUS|freighteasy/images/footer_legal.gif FSUS|freighteasy/images/footer_middle.gif FHUS|contact.asp FSUS|freighteasy/images/footer_contact.gif FSUS|freighteasy/images/spacer.gif FSUS|freighteasy/images/footer.gif FSUS|freighteasy/images/spacer.gif
vti_cachedneedsrewrite:BR|true
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|keywords Freight\\ Forwarders,\\ IFF,\\ software,\\ NVOCC,\\ Import,\\ Export,\\ supply\\ chain\\ management,\\ HAWB,\\ MAWB,\\ SED,\\ deconsolidation description software\\ solution\\ for\\ Freight\\ Forwarders,\\ logistics\\ solution HTTP-EQUIV=Content-Type text/html;\\ charset=iso-8859-1
vti_charset:SR|windows-1252
vti_title:SR|FreightEasy-A complete Freight Forwarding System Made Easy
vti_lineageid:SR|{A08629CB-63A0-437E-9835-7FBA9C3B4492}
vti_backlinkinfo:VX|freighteasy/freighteasy.aspx
