<%
'/////////////////////////////////////////////////////////
'// Constants for Account Type ///////////////////////////
'/////////////////////////////////////////////////////////
Const CONST__MASTER_ASSET_NAME     = "ASSET"
	Const CONST__CURRENT_ASSET = "Current Asset"
	Const CONST__ACCOUNT_RECEIVABLE   = "Accounts Receivable"
	Const CONST__FIXED_ASSET   = "Fixed Asset"
	Const CONST__OTHER_ASSET   = "Other Asset"
	Const CONST__BANK   = "Cash in Bank"
Const CONST__MASTER_LIABILITY_NAME = "LIABILITY"
	Const CONST__CURRENT_LIB   = "Current Liability"
	Const CONST__ACCOUNT_PAYABLE   = "Accounts Payable"
	Const CONST__LONG_TERM_LIB = "Long-Term Liability"

Const CONST__MASTER_EQUITY_NAME    = "EQUITY"
	Const CONST__EQUITY        = "Equity"
	Const CONST__EQUITY_RETAINED_EARNINGS = "Equity-Retained Earnings"
Const CONST__MASTER_REVENUE_NAME   = "REVENUE"
	Const CONST__REVENUE       = "Revenue"
	Const CONST__OTHER_REVENUE = "Other Revenue"

Const CONST__MASTER_EXPENSE_NAME   = "EXPENSE"
	Const CONST__EXPENSE       = "Expense"
	Const CONST__COST_OF_SALES = "Cost of Sales"
	Const CONST__OTHER_EXPENSE = "Other Expense"
%>

