CREATE TABLE [dbo].[account_request] (
    [auto_uid]             DECIMAL (18)  IDENTITY (1, 1) NOT NULL,
    [dba_name]             NVARCHAR (50) NULL,
    [business_legal_name]  NVARCHAR (50) NULL,
    [business_address]     NVARCHAR (50) NULL,
    [business_address_add] NVARCHAR (50) NULL,
    [business_city]        NVARCHAR (50) NULL,
    [business_state]       NVARCHAR (50) NULL,
    [business_province]    NVARCHAR (50) NULL,
    [business_zip]         NVARCHAR (50) NULL,
    [business_country]     NVARCHAR (50) NULL,
    [country_code]         NVARCHAR (8)  NULL,
    [business_phone]       NVARCHAR (50) NULL,
    [business_fax]         NVARCHAR (50) NULL,
    [business_url]         NVARCHAR (50) NULL,
    [admin_pass]           NVARCHAR (50) NULL,
    [admin_id]             NVARCHAR (50) NULL,
    [owner_lname]          NVARCHAR (50) NULL,
    [owner_fname]          NVARCHAR (50) NULL,
    [owner_mail_address]   NVARCHAR (50) NULL,
    [owner_mail_city]      NVARCHAR (50) NULL,
    [owner_mail_state]     NVARCHAR (50) NULL,
    [owner_mail_zip]       NVARCHAR (50) NULL,
    [owner_mail_country]   NVARCHAR (50) NULL,
    [owner_phone]          NVARCHAR (50) NULL,
    [owner_email]          NVARCHAR (50) NULL,
    [account_type]         NVARCHAR (1)  NULL,
    [payment_id]           DECIMAL (18)  NULL
);

