CREATE TABLE [dbo].[aes_master] (
    [auto_uid]             DECIMAL (18)  IDENTITY (1, 1) NOT NULL,
    [elt_account_number]   DECIMAL (8)   NOT NULL,
    [party_to_transaction] NVARCHAR (1)  NULL,
    [export_date]          DATETIME      NULL,
    [tran_ref_no]          NVARCHAR (30) NULL,
    [consignee_acct]       DECIMAL (6)   NULL,
    [inter_consignee_acct] DECIMAL (18)  NULL,
    [origin_state]         NVARCHAR (16) NULL,
    [dest_country]         NVARCHAR (2)  NULL,
    [tran_method]          NVARCHAR (2)  NULL,
    [export_carrier]       NVARCHAR (23) NULL,
    [export_port]          NVARCHAR (5)  NULL,
    [unloading_port]       NVARCHAR (5)  NULL,
    [carrier_id_code]      NVARCHAR (4)  NULL,
    [shipment_ref_no]      NVARCHAR (17) NULL,
    [entry_no]             NVARCHAR (15) NULL,
    [hazardous_materials]  NVARCHAR (1)  NULL,
    [in_bond_type]         NVARCHAR (2)  NULL,
    [in_bond_no]           NVARCHAR (15) NULL,
    [route_export_tran]    NVARCHAR (1)  NULL,
    [tran_date]            DATETIME      NULL,
    [last_modified]        DATETIME      NULL,
    [aes_itn]              NVARCHAR (32) NULL,
    [aes_status]           NVARCHAR (32) NULL,
    [ftz]                  NVARCHAR (5)  NULL,
    [agent_acct]           DECIMAL (18)  NULL,
    [shipper_acct]         DECIMAL (18)  NULL,
    [file_type]            NVARCHAR (2)  NULL,
    [house_num]            NVARCHAR (50) NULL,
    [master_num]           NVARCHAR (50) NULL,
    CONSTRAINT [PK_aes_master] PRIMARY KEY CLUSTERED ([auto_uid] ASC)
);

