CREATE TABLE [dbo].[agent] (
    [elt_account_number]   DECIMAL (8)     NOT NULL,
    [dba_name]             NVARCHAR (128)  NOT NULL,
    [class_code]           NCHAR (1)       NULL,
    [date_opened]          DATETIME        NULL,
    [business_legal_name]  NVARCHAR (128)  NULL,
    [business_fed_taxid]   NVARCHAR (16)   NULL,
    [business_st_taxid]    NVARCHAR (16)   NULL,
    [usppi]                NVARCHAR (64)   NULL,
    [business_address]     NVARCHAR (128)  NULL,
    [business_address_add] NVARCHAR (128)  NULL,
    [business_city]        NVARCHAR (64)   NULL,
    [business_province]    NVARCHAR (128)  NULL,
    [business_state]       NVARCHAR (128)  NULL,
    [business_zip]         NVARCHAR (32)   NULL,
    [business_country]     NVARCHAR (32)   NULL,
    [country_code]         NVARCHAR (2)    NULL,
    [business_phone]       NVARCHAR (32)   NULL,
    [business_fax]         NVARCHAR (32)   NULL,
    [business_url]         NVARCHAR (64)   NULL,
    [owner_ssn]            NVARCHAR (9)    NULL,
    [owner_lname]          NVARCHAR (64)   NULL,
    [owner_fname]          NVARCHAR (64)   NULL,
    [owner_mname]          NVARCHAR (32)   NULL,
    [owner_mail_address]   NVARCHAR (128)  NULL,
    [owner_mail_city]      NVARCHAR (64)   NULL,
    [owner_mail_state]     NVARCHAR (128)  NULL,
    [owner_mail_zip]       NVARCHAR (32)   NULL,
    [owner_mail_country]   NVARCHAR (32)   NULL,
    [owner_phone]          NVARCHAR (32)   NULL,
    [owner_email]          NVARCHAR (128)  NULL,
    [account_statue]       NCHAR (1)       NULL,
    [Agent_IATA_Code]      NVARCHAR (32)   NULL,
    [OTI_Code]             NVARCHAR (50)   NULL,
    [board_name]           NVARCHAR (32)   NULL,
    [iv_statement]         NVARCHAR (1024) NULL,
    [faa_approval_no]      NVARCHAR (32)   NULL,
    [maxuser]              DECIMAL (18)    NULL,
    [is_dome]              NVARCHAR (1)    CONSTRAINT [DF__agent__is_dome__27E3DFFF] DEFAULT ('N') NOT NULL,
    [is_intl]              NVARCHAR (1)    CONSTRAINT [DF__agent__is_intl__28D80438] DEFAULT ('Y') NOT NULL,
    [faa_approval_date]    NVARCHAR (64)   NULL,
    [is_cartage]           NVARCHAR (1)    CONSTRAINT [DF__agent__is_cartag__5B638405] DEFAULT ('N') NULL,
    [is_warehouse]         NVARCHAR (1)    NULL,
    [is_accounting]        NVARCHAR (1)    NULL,
    [is_exporter]          NVARCHAR (1)    CONSTRAINT [DF__agent__is_AES__477199F1] DEFAULT ('N') NULL,
    [is_aes]               NVARCHAR (1)    NULL,
    [ID]                   INT             IDENTITY (1, 1) NOT NULL
);

