CREATE TABLE [dbo].[booking_confirm] (
    [auto_uid]                     DECIMAL (18)   IDENTITY (1, 1) NOT NULL,
    [bc_no]                        NVARCHAR (64)  NULL,
    [elt_account_number]           DECIMAL (18)   NULL,
    [document_date]                DATETIME       NULL,
    [air_ocean]                    NVARCHAR (1)   NULL,
    [booking_no]                   NVARCHAR (64)  NULL,
    [master_no]                    NVARCHAR (64)  NULL,
    [house_no]                     NVARCHAR (64)  NULL,
    [sub_house_no]                 NVARCHAR (32)  NULL,
    [shipper_acct]                 DECIMAL (18)   NULL,
    [shipper_name]                 NVARCHAR (128) NULL,
    [shipper_info]                 NTEXT          NULL,
    [deliver_to_acct]              DECIMAL (18)   NULL,
    [deliver_to_name]              NVARCHAR (128) NULL,
    [deliver_to_info]              NTEXT          NULL,
    [cut_off_date]                 NVARCHAR (50)  NULL,
    [export_reference]             NVARCHAR (64)  NULL,
    [carrier_acct]                 DECIMAL (18)   NULL,
    [carrier_name]                 NVARCHAR (128) NULL,
    [carrier_no]                   NVARCHAR (128) NULL,
    [place_of_receipt]             NVARCHAR (128) NULL,
    [place_of_delivery]            NVARCHAR (128) NULL,
    [dep_port]                     NVARCHAR (128) NULL,
    [arr_port]                     NVARCHAR (128) NULL,
    [eta]                          DATETIME       NULL,
    [etd]                          DATETIME       NULL,
    [move_type]                    NVARCHAR (32)  NULL,
    [dest_agent_acct]              DECIMAL (18)   NULL,
    [dest_agent_name]              NVARCHAR (128) NULL,
    [dest_agent_info]              NTEXT          NULL,
    [empty_container_pick_up_acct] DECIMAL (18)   NULL,
    [empty_container_pick_up_name] NVARCHAR (128) NULL,
    [empty_container_pick_up_info] NTEXT          NULL,
    [dangerous]                    NVARCHAR (50)  NULL,
    [quantity]                     DECIMAL (18)   NULL,
    [quantity_unit]                NVARCHAR (50)  NULL,
    [item_desc]                    NTEXT          NULL,
    [gross_weight]                 DECIMAL (18)   NULL,
    [weight_scale]                 NVARCHAR (3)   NULL,
    [dimension]                    DECIMAL (18)   NULL,
    [dimension_scale]              NVARCHAR (3)   NULL,
    [remark]                       NTEXT          NULL,
    CONSTRAINT [PK_booking_confirm] PRIMARY KEY CLUSTERED ([auto_uid] ASC)
);

