CREATE TABLE [dbo].[cargo_tracking] (
    [elt_account_number]    DECIMAL (8)     CONSTRAINT [DF_cargo_tracking_elt_account_number] DEFAULT (0) NULL,
    [request_id]            DECIMAL (8)     CONSTRAINT [DF_cargo_tracking_request_id] DEFAULT (0) NULL,
    [export_agent_name]     NVARCHAR (255)  NULL,
    [import_agent_elt_acct] DECIMAL (8)     CONSTRAINT [DF_cargo_tracking_import_agent_elt_acct] DEFAULT (0) NULL,
    [import_agent_name]     NVARCHAR (128)  NULL,
    [ref_no]                NVARCHAR (64)   NULL,
    [sr_dt]                 DATETIME        NULL,
    [sr_location]           NVARCHAR (255)  NULL,
    [shipper_name]          NVARCHAR (128)  NULL,
    [shipper_info]          NVARCHAR (256)  NULL,
    [shipper_acct]          DECIMAL (8)     CONSTRAINT [DF_cargo_tracking_shipper_acct] DEFAULT (0) NULL,
    [consignee_name]        NVARCHAR (128)  NULL,
    [consignee_acct]        DECIMAL (8)     NULL,
    [consignee_import_acct] DECIMAL (8)     CONSTRAINT [DF_cargo_tracking_consignee_import_acct] DEFAULT (0) NULL,
    [flight_no]             NVARCHAR (16)   NULL,
    [etd]                   DATETIME        NULL,
    [eta]                   DATETIME        NULL,
    [pol]                   NVARCHAR (32)   NULL,
    [poa]                   NVARCHAR (32)   NULL,
    [pieces]                INT             CONSTRAINT [DF_cargo_tracking_pieces] DEFAULT (0) NULL,
    [pc_scale]              NVARCHAR (8)    NULL,
    [chg_wt]                DECIMAL (10, 2) CONSTRAINT [DF_cargo_tracking_chg_wt] DEFAULT (0) NULL,
    [chg_wt_scale]          NVARCHAR (8)    NULL,
    [gross_wt]              DECIMAL (12, 2) CONSTRAINT [DF_cargo_tracking_gross_wt] DEFAULT (0) NULL,
    [gross_wt_scale]        NVARCHAR (8)    NULL,
    [dims]                  DECIMAL (12, 2) CONSTRAINT [DF_cargo_tracking_dims] DEFAULT (0) NULL,
    [dims_scale]            NVARCHAR (8)    NULL,
    [sr_by]                 NVARCHAR (64)   NULL,
    [pu_location]           NVARCHAR (128)  NULL,
    [pickup_dt]             DATETIME        NULL,
    [airport_dt]            DATETIME        NULL,
    [ready_dt]              NVARCHAR (50)   NULL,
    [contact]               NVARCHAR (64)   NULL,
    [contact_phone]         NVARCHAR (64)   NULL,
    [hawb]                  NVARCHAR (32)   NULL,
    [mawb]                  NVARCHAR (32)   NULL,
    [note]                  NTEXT           NULL,
    [invoice_no]            DECIMAL (12)    CONSTRAINT [DF_cargo_tracking_invoice_no] DEFAULT (0) NULL,
    [cargo_location]        NVARCHAR (256)  NULL,
    [it_number]             DECIMAL (12)    CONSTRAINT [DF_cargo_tracking_it_number] DEFAULT (0) NULL,
    [wh1_in_tran_dt]        DATETIME        NULL,
    [wh1_in_dt]             DATETIME        NULL,
    [wh1_in_pc]             INT             NULL,
    [wh1_from]              NVARCHAR (50)   NULL,
    [wh1_in_trucker]        NVARCHAR (50)   NULL,
    [wh1_in_remark]         NTEXT           NULL,
    [wh1_out_tran_dt]       DATETIME        NULL,
    [wh1_out_dt]            DATETIME        NULL,
    [wh1_out_pc]            INT             NULL,
    [wh1_to]                NVARCHAR (64)   NULL,
    [wh1_out_trucker]       NVARCHAR (64)   NULL,
    [wh1_out_remark]        NTEXT           NULL,
    [wh2_in_tran_dt]        DATETIME        NULL,
    [wh2_in_dt]             DATETIME        NULL,
    [wh2_in_pc]             INT             NULL,
    [wh2_from]              NVARCHAR (50)   NULL,
    [wh2_in_trucker]        NVARCHAR (50)   NULL,
    [wh2_in_remark]         NTEXT           NULL,
    [wh2_out_tran_dt]       DATETIME        NULL,
    [wh2_out_dt]            DATETIME        NULL,
    [wh2_out_pc]            INT             NULL,
    [wh2_to]                NVARCHAR (54)   NULL,
    [wh2_out_trucker]       NVARCHAR (64)   NULL,
    [wh2_out_remark]        NTEXT           NULL,
    [dest_tran_dt]          DATETIME        NULL,
    [dest_from]             NVARCHAR (50)   NULL,
    [dest_dt]               DATETIME        NULL,
    [dest_pc]               INT             NULL,
    [dest_trucker]          NVARCHAR (50)   NULL,
    [dest_remark]           NTEXT           NULL,
    [dest_close_remark]     NTEXT           NULL,
    [dest_close_dt]         DATETIME        NULL,
    [status]                NCHAR (1)       NULL,
    [is_org_merged]         NCHAR (1)       NULL
);

