CREATE TABLE [dbo].[certificate_origin_air] (
    [auto_uid]           DECIMAL (18)   IDENTITY (1, 1) NOT NULL,
    [doc_num]            NVARCHAR (64)  NULL,
    [hawb_num]           NVARCHAR (64)  NULL,
    [mawb_num]           NVARCHAR (64)  NULL,
    [elt_account_number] DECIMAL (18)   NULL,
    [shipper_name]       NVARCHAR (128) NULL,
    [shipper_info]       NTEXT          NULL,
    [shipper_acct_num]   DECIMAL (18)   NULL,
    [consignee_name]     NVARCHAR (128) NULL,
    [consignee_info]     NTEXT          NULL,
    [consignee_acct_num] DECIMAL (18)   NULL,
    [agent_name]         NVARCHAR (128) NULL,
    [agent_info]         NTEXT          NULL,
    [agent_acct_num]     DECIMAL (18)   NULL,
    [notify_name]        NVARCHAR (128) NULL,
    [notify_info]        NTEXT          NULL,
    [notify_acct_num]    DECIMAL (18)   NULL,
    [export_ref]         NTEXT          NULL,
    [origin_country]     NVARCHAR (128) NULL,
    [export_instr]       NTEXT          NULL,
    [pre_carriage]       NVARCHAR (128) NULL,
    [pre_receipt_place]  NVARCHAR (128) NULL,
    [export_carrier]     NVARCHAR (128) NULL,
    [loading_port]       NVARCHAR (64)  NULL,
    [loading_terminal]   NVARCHAR (64)  NULL,
    [unloading_port]     NVARCHAR (64)  NULL,
    [delivery_place]     NVARCHAR (64)  NULL,
    [move_type]          NVARCHAR (64)  NULL,
    [updated_date]       DATETIME       NULL,
    [file_name]          NVARCHAR (128) NULL,
    [anonymous]          NVARCHAR (1)   CONSTRAINT [DF_certificate_origin_air_anonymous] DEFAULT ('N') NULL,
    [us_state]           NVARCHAR (64)  NULL,
    [dest_country]       NVARCHAR (128) NULL,
    [shipping_city]      NVARCHAR (128) NULL,
    [ff_name]            NVARCHAR (128) NULL,
    [ff_city]            NVARCHAR (128) NULL,
    [ff_county]          NVARCHAR (128) NULL,
    [created_date]       DATETIME       NULL,
    [sworn_date]         DATETIME       NULL,
    [employee]           NVARCHAR (128) NULL,
    [origin_state]       NVARCHAR (64)  NULL,
    [is_org_merged]      NCHAR (1)      NULL,
    [session_id]         NVARCHAR (64)  NULL,
    [ff_county_acct]     DECIMAL (9)    NULL,
    [ff_county_name]     NVARCHAR (128) NULL
);

