CREATE TABLE [dbo].[delivery_order] (
    [auto_uid]           DECIMAL (18)   IDENTITY (1, 1) NOT NULL,
    [elt_account_number] DECIMAL (18)   NULL,
    [mawb_no]            NVARCHAR (64)  NULL,
    [hawb_no]            NVARCHAR (64)  NULL,
    [sub_hawb_no]        NVARCHAR (32)  NULL,
    [shipper_name]       NVARCHAR (128) NULL,
    [shipper_info]       NTEXT          NULL,
    [shipper_acct]       DECIMAL (18)   NULL,
    [consignee_name]     NVARCHAR (128) NULL,
    [consignee_info]     NTEXT          NULL,
    [consignee_acct]     DECIMAL (18)   NULL,
    [update_date]        DATETIME       NULL,
    [ref_no_Our]         NVARCHAR (32)  NULL,
    [carrier_name]       NVARCHAR (128) NULL,
    [carrier_info]       NTEXT          NULL,
    [cargo_location]     NVARCHAR (128) NULL,
    [iType]              NVARCHAR (1)   NULL,
    [dep_port]           NVARCHAR (128) NULL,
    [arr_port]           NVARCHAR (128) NULL,
    [eta]                DATETIME       NULL,
    [etd]                DATETIME       NULL,
    [free_date]          DATETIME       NULL,
    [trucker_name]       NVARCHAR (128) NULL,
    [trucker_info]       NTEXT          NULL,
    [trucker_acct]       NVARCHAR (64)  NULL,
    [entry_billing_no]   NVARCHAR (32)  NULL,
    [customer_ref_no]    NVARCHAR (32)  NULL,
    [item_pieces]        NVARCHAR (64)  NULL,
    [item_desc]          NTEXT          NULL,
    [item_gross_wt]      FLOAT (53)     NULL,
    [item_scale]         NVARCHAR (3)   NULL,
    [inland_charge]      FLOAT (53)     NULL,
    [inland_charge_type] NVARCHAR (1)   NULL,
    [route]              NTEXT          NULL,
    [sec_num]            NVARCHAR (32)  NULL,
    [handling]           NVARCHAR (128) NULL,
    [attention]          NVARCHAR (128) NULL,
    [employee]           NVARCHAR (128) NULL,
    [anonymous]          NVARCHAR (1)   CONSTRAINT [DF_delivery_order_anonymous] DEFAULT ('N') NULL,
    [file_name]          NVARCHAR (128) NULL,
    [pickupfrom]         NVARCHAR (256) NULL,
    [is_org_merged]      NCHAR (1)      NULL,
    [session_id]         NVARCHAR (64)  NULL,
    [Carrier_Code]       NVARCHAR (64)  NULL,
    [importer_acct]      DECIMAL (18)   NULL,
    [importer_name]      NVARCHAR (128) NULL,
    [importer_info]      NTEXT          NULL,
    [pickup_acct]        DECIMAL (18)   NULL,
    [pickup_name]        NVARCHAR (128) NULL,
    [pickup_info]        NTEXT          NULL,
    [dep_port_code]      NVARCHAR (8)   NULL,
    [arr_port_code]      NVARCHAR (8)   NULL,
    [delivery_ref_num]   NVARCHAR (32)  NULL,
    [dimension]          NVARCHAR (128) NULL,
    [dimension_scale]    NVARCHAR (3)   NULL
);

