CREATE TABLE [dbo].[email_history] (
    [auto_uid]           DECIMAL (18)   IDENTITY (1, 1) NOT NULL,
    [email_id]           NVARCHAR (64)  NULL,
    [elt_account_number] DECIMAL (18)   NULL,
    [user_id]            DECIMAL (18)   NULL,
    [to_org_id]          DECIMAL (18)   NULL,
    [to_org_name]        NVARCHAR (128) NULL,
    [email_sender]       NVARCHAR (128) NULL,
    [email_from]         NVARCHAR (128) NULL,
    [email_to]           NVARCHAR (128) NULL,
    [email_cc]           NVARCHAR (128) NULL,
    [email_subject]      NVARCHAR (256) NULL,
    [email_content]      NTEXT          NULL,
    [sent_date]          DATETIME       NULL,
    [sent_status]        NVARCHAR (32)  NULL,
    [air_ocean]          NVARCHAR (1)   NULL,
    [im_export]          NVARCHAR (1)   NULL,
    [screen_name]        NVARCHAR (64)  NULL,
    [master_num]         NVARCHAR (32)  NULL,
    [house_num]          NTEXT          NULL,
    [manifest_link]      NTEXT          NULL,
    [invoice_num]        NTEXT          NULL,
    [attached_files]     NTEXT          NULL,
    [attached_pdf]       NTEXT          NULL,
    [online_alert]       NVARCHAR (1)   NULL,
    [is_org_merged]      NCHAR (1)      NULL,
    CONSTRAINT [PK_email_history] PRIMARY KEY CLUSTERED ([auto_uid] ASC)
);

