CREATE TABLE [dbo].[HAWB_master_add] (
    [auto_uid]            DECIMAL (18)   IDENTITY (1, 1) NOT NULL,
    [hawb_num]            NVARCHAR (64)  NULL,
    [mawb_num]            NVARCHAR (64)  NULL,
    [is_agent_house]      NVARCHAR (1)   CONSTRAINT [DF_HAWB_master_add_is_agent_house] DEFAULT ('N') NULL,
    [elt_account_number]  DECIMAL (18)   NULL,
    [customer_acct]       DECIMAL (18)   NULL,
    [billto_acct]         DECIMAL (18)   NULL,
    [ship_status]         NVARCHAR (1)   NULL,
    [pickup_alert_date]   NVARCHAR (10)  NULL,
    [pickup_alert_time]   NVARCHAR (8)   NULL,
    [ready_date]          NVARCHAR (10)  NULL,
    [ready_time]          NVARCHAR (8)   NULL,
    [close_date]          NVARCHAR (10)  NULL,
    [close_time]          NVARCHAR (8)   NULL,
    [pickup_date]         NVARCHAR (10)  NULL,
    [pickup_time]         NVARCHAR (8)   NULL,
    [dispatch_date]       NVARCHAR (10)  NULL,
    [dispatch_time]       NVARCHAR (8)   NULL,
    [onboard_date]        NVARCHAR (10)  NULL,
    [onboard_time]        NVARCHAR (8)   NULL,
    [transfer_date]       NVARCHAR (10)  NULL,
    [transfer_time]       NVARCHAR (8)   NULL,
    [carrier_signer]      NVARCHAR (128) NULL,
    [delivery_alert_date] NVARCHAR (10)  NULL,
    [delivery_alert_time] NVARCHAR (50)  NULL,
    [recover_date]        NVARCHAR (50)  NULL,
    [recover_time]        NVARCHAR (50)  NULL,
    [OFD_date]            NVARCHAR (50)  NULL,
    [OFD_time]            NVARCHAR (50)  NULL,
    [POD_date]            NVARCHAR (50)  NULL,
    [POD_time]            NVARCHAR (50)  NULL,
    [POD_signer]          NVARCHAR (128) NULL,
    [ship_time_status]    NVARCHAR (32)  NULL
);

