CREATE TABLE [dbo].[HAWB_master] (
    [elt_account_number]                  DECIMAL (8)     NOT NULL,
    [HAWB_NUM]                            NVARCHAR (32)   NOT NULL,
    [MAWB_NUM]                            NVARCHAR (64)   NULL,
    [DEP_AIRPORT_CODE]                    NVARCHAR (3)    NULL,
    [airline_vendor_num]                  DECIMAL (5)     NULL,
    [Agent_Name]                          NVARCHAR (128)  NULL,
    [Agent_Info]                          NTEXT           NULL,
    [Agent_No]                            DECIMAL (7)     NULL,
    [Shipper_Name]                        NVARCHAR (128)  NULL,
    [Shipper_Info]                        NTEXT           NULL,
    [Shipper_account_number]              NVARCHAR (16)   NULL,
    [ff_shipper_acct]                     NVARCHAR (64)   NULL,
    [Consignee_Name]                      NVARCHAR (256)  NULL,
    [Consignee_Info]                      NTEXT           NULL,
    [Consignee_acct_num]                  NVARCHAR (32)   NULL,
    [ff_consignee_acct]                   NVARCHAR (64)   NULL,
    [Issue_Carrier_agent]                 NTEXT           NULL,
    [Agent_IATA_Code]                     NVARCHAR (32)   NULL,
    [Account_No]                          NVARCHAR (32)   NULL,
    [Departure_Airport]                   NVARCHAR (64)   NULL,
    [departure_state]                     NVARCHAR (16)   NULL,
    [IssuedBy]                            NTEXT           NULL,
    [Account_Info]                        NTEXT           NULL,
    [to_1]                                NVARCHAR (8)    NULL,
    [by_1]                                NVARCHAR (64)   NULL,
    [to_2]                                NVARCHAR (8)    NULL,
    [by_2]                                NVARCHAR (64)   NULL,
    [to_3]                                NVARCHAR (8)    NULL,
    [by_3]                                NVARCHAR (64)   NULL,
    [Currency]                            NVARCHAR (3)    NULL,
    [Charge_Code]                         NVARCHAR (10)   NULL,
    [PPO_1]                               NVARCHAR (1)    NULL,
    [COLL_1]                              NVARCHAR (1)    NULL,
    [PPO_2]                               NVARCHAR (1)    NULL,
    [COLL_2]                              NVARCHAR (1)    NULL,
    [Declared_Value_Carriage]             NVARCHAR (16)   NULL,
    [Declared_Value_Customs]              NVARCHAR (16)   NULL,
    [Dest_Airport]                        NVARCHAR (64)   NULL,
    [flight_no]                           NVARCHAR (12)   NULL,
    [Flight_Date_1]                       NVARCHAR (32)   NULL,
    [Flight_Date_2]                       NVARCHAR (32)   NULL,
    [export_date]                         DATETIME        NULL,
    [Insurance_AMT]                       NVARCHAR (16)   NULL,
    [Handling_Info]                       NTEXT           NULL,
    [dest_country]                        NVARCHAR (128)  NULL,
    [SCI]                                 NVARCHAR (16)   NULL,
    [Total_Pieces]                        DECIMAL (18)    NULL,
    [Adjusted_Weight]                     DECIMAL (12, 2) NULL,
    [Total_Gross_Weight]                  DECIMAL (12, 2) NULL,
    [Total_Chargeable_Weight]             DECIMAL (12, 2) NULL,
    [Weight_Scale]                        NCHAR (1)       NULL,
    [Total_Weight_Charge_HAWB]            DECIMAL (12, 2) NULL,
    [total_other_cost]                    DECIMAL (18, 2) NULL,
    [af_cost]                             DECIMAL (12, 2) CONSTRAINT [DF_HAWB_master_af_cost] DEFAULT (0) NULL,
    [agent_profit]                        DECIMAL (12, 2) CONSTRAINT [DF_HAWB_master_agent_profit] DEFAULT (0) NULL,
    [agent_profit_share]                  DECIMAL (3, 2)  CONSTRAINT [DF_HAWB_master_agent_profit_share] DEFAULT (0) NULL,
    [other_agent_profit_carrier]          DECIMAL (12, 2) CONSTRAINT [DF_HAWB_master_other_agent_profit_carrier] DEFAULT (0) NULL,
    [other_agent_profit_agent]            DECIMAL (12, 2) CONSTRAINT [DF_HAWB_master_other_agent_profit_agent] DEFAULT (0) NULL,
    [Total_Weight_Charge_ACCT]            DECIMAL (12, 2) NULL,
    [Total_Other_Charges]                 DECIMAL (12, 2) NULL,
    [Prepaid_Weight_Charge]               DECIMAL (12, 2) NULL,
    [Collect_Weight_Charge]               DECIMAL (12, 2) NULL,
    [Prepaid_Valuation_Charge]            DECIMAL (12, 2) NULL,
    [Collect_Valuation_Charge]            DECIMAL (12, 2) NULL,
    [Prepaid_Tax]                         DECIMAL (12, 2) NULL,
    [Collect_Tax]                         DECIMAL (12, 2) NULL,
    [Prepaid_Due_Agent]                   DECIMAL (12, 2) NULL,
    [Collect_Due_Agent]                   DECIMAL (12, 2) NULL,
    [Prepaid_Due_Carrier]                 DECIMAL (12, 2) NULL,
    [Collect_Due_Carrier]                 DECIMAL (12, 2) NULL,
    [Prepaid_Unused]                      DECIMAL (12, 2) NULL,
    [Collect_Unused]                      DECIMAL (12, 2) NULL,
    [Prepaid_Total]                       DECIMAL (12, 2) NULL,
    [Collect_Total]                       DECIMAL (12, 2) NULL,
    [Signature]                           NTEXT           NULL,
    [Date_Executed]                       DATETIME        NULL,
    [Execution]                           NTEXT           NULL,
    [Date_Last_Modified]                  DATETIME        NULL,
    [Currency_Conv_Rate]                  DECIMAL (10, 2) NULL,
    [CC_Charge_Dest_Rate]                 DECIMAL (10, 2) NULL,
    [Charge_at_Dest]                      DECIMAL (12, 2) NULL,
    [Total_Collect_Charge]                DECIMAL (12, 2) NULL,
    [Desc1]                               NTEXT           NULL,
    [Desc2]                               NTEXT           NULL,
    [manifest_desc]                       NTEXT           NULL,
    [lc]                                  NVARCHAR (128)  NULL,
    [ci]                                  NVARCHAR (128)  NULL,
    [other_ref]                           NVARCHAR (128)  NULL,
    [Show_Weight_Charge_Shipper]          NCHAR (1)       NULL,
    [Show_Weight_Charge_Consignee]        NCHAR (1)       NULL,
    [Show_Prepaid_Other_Charge_Shipper]   NCHAR (1)       NULL,
    [Show_Collect_Other_Charge_Shipper]   NCHAR (1)       NULL,
    [Show_Prepaid_Other_Charge_Consignee] NCHAR (1)       NULL,
    [Show_Collect_Other_Charge_Consignee] NCHAR (1)       NULL,
    [Prepaid_Invoiced]                    NCHAR (1)       NULL,
    [Collect_Invoiced]                    NCHAR (1)       NULL,
    [colo]                                NCHAR (1)       CONSTRAINT [DF_HAWB_master_colo] DEFAULT ('N') NULL,
    [colo_pay]                            NCHAR (1)       NULL,
    [coloder_elt_acct]                    DECIMAL (8)     NULL,
    [coloder_invoiced]                    NCHAR (1)       NULL,
    [Notify_no]                           NVARCHAR (32)   NULL,
    [SalesPerson]                         NVARCHAR (64)   NULL,
    [CreatedBy]                           NVARCHAR (64)   NULL,
    [CreatedDate]                         DATETIME        NULL,
    [ModifiedBy]                          NVARCHAR (64)   NULL,
    [ModifiedDate]                        DATETIME        NULL,
    [aes_xtn]                             NVARCHAR (64)   NULL,
    [rate_on]                             NCHAR (2)       NULL,
    [is_sub]                              NCHAR (1)       NULL,
    [is_master]                           NCHAR (1)       NULL,
    [sub_to_no]                           NVARCHAR (32)   NULL,
    [sub_no]                              INT             NULL,
    [is_master_closed]                    NCHAR (1)       NULL,
    [is_invoice_queued]                   NCHAR (1)       NULL,
    [is_org_merged]                       NCHAR (1)       NULL,
    [master_weight_charge]                DECIMAL (12, 2) NULL,
    [master_pieces]                       DECIMAL (4)     NULL,
    [master_gross_weight]                 DECIMAL (12, 2) NULL,
    [master_chargeable_weight]            DECIMAL (12, 2) NULL,
    [dimtext]                             NTEXT           NULL,
    [reference_number]                    NVARCHAR (32)   NULL,
    [sub_count]                           NCHAR (1)       NULL,
    [is_dome]                             NVARCHAR (1)    CONSTRAINT [DF__hawb_mast__is_do__25077354] DEFAULT ('N') NOT NULL,
    [iac_num]                             NVARCHAR (32)   NULL,
    [service_level_other]                 NVARCHAR (64)   NULL,
    [PO_num]                              NVARCHAR (32)   NULL,
    [purchase_num]                        NVARCHAR (64)   NULL,
    [shipper_reference_num]               NVARCHAR (64)   NULL,
    [service_level]                       NVARCHAR (128)  NULL,
    [cod_amount]                          DECIMAL (10, 2) NULL,
    [shipper_cod_amount]                  DECIMAL (10, 2) NULL,
    [bill_to_party]                       NVARCHAR (1)    NULL,
    [danger_good]                         NVARCHAR (1)    NULL,
    [show_weight_charge_rate]             NVARCHAR (1)    CONSTRAINT [DF__HAWB_mast__show___5792F321] DEFAULT ('Y') NULL,
    [show_other_charge_rate]              NVARCHAR (1)    CONSTRAINT [DF__HAWB_mast__show___5887175A] DEFAULT ('Y') NULL,
    [is_agent_house]                      NVARCHAR (1)    CONSTRAINT [DF__hawb_mast__is_ag__5C57A83E] DEFAULT ('N') NULL,
    [is_inbound]                          NVARCHAR (1)    CONSTRAINT [DF__hawb_mast__is_in__67C95AEA] DEFAULT ('N') NULL,
    [sed_stmt]                            NVARCHAR (128)  NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [PK_hawb_master]
    ON [dbo].[HAWB_master]([elt_account_number] ASC, [HAWB_NUM] ASC, [MAWB_NUM] ASC);


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-HAWB_master]
    ON [dbo].[HAWB_master]([MAWB_NUM] ASC);

