CREATE TABLE [dbo].[ig_ocean_ams_edi_header] (
    [elt_account_number]              DECIMAL (18)  NOT NULL,
    [doc_number]                      DECIMAL (18)  NOT NULL,
    [v1_vessel_code]                  NCHAR (7)     NULL,
    [v2_voyage_number]                NCHAR (5)     NULL,
    [v3_vessel_name]                  NCHAR (23)    NULL,
    [v4_scac_code]                    NCHAR (4)     NULL,
    [v5_vessel_flag]                  NCHAR (2)     NULL,
    [v6_first_us_port_of_discharge]   NCHAR (5)     NULL,
    [v7_last_foreign_pol_s]           NCHAR (32)    NULL,
    [v7_last_foreign_pol]             NCHAR (5)     NULL,
    [p1_port_of_discharge]            NCHAR (5)     NULL,
    [p2_estimated_date_of_arrival]    DATETIME      NULL,
    [p3_terminal_operator_code_s]     NCHAR (32)    NULL,
    [p3_terminal_operator_code]       NCHAR (5)     NULL,
    [l1_port_of_load_s]               NCHAR (32)    NULL,
    [l1_port_of_load]                 NCHAR (5)     NULL,
    [l2_load_date]                    DATETIME      NULL,
    [l3_load_time]                    SMALLDATETIME NULL,
    [creation_date]                   DATETIME      NULL,
    [b1_bill_of_lading_number]        NCHAR (12)    NULL,
    [b2_port_of_loading_s]            NCHAR (32)    NULL,
    [b2_port_of_loading]              NCHAR (5)     NULL,
    [b3_place_of_final_destination_s] NCHAR (32)    NULL,
    [b3_place_of_final_destination]   NCHAR (5)     NULL,
    [b4_place_of_receipt]             NCHAR (17)    NULL,
    [b5_b_lading_status_code]         NCHAR (1)     NULL,
    [b6_b_lading_issuer_scac_code]    NCHAR (4)     NULL,
    [b7_snp1]                         NCHAR (4)     NULL,
    [b8_snp2]                         NCHAR (4)     NULL,
    [b9_manifested_units]             NCHAR (5)     NULL,
    [b10_total_gross_weight]          NCHAR (10)    NULL,
    [b11_booking_number]              NCHAR (30)    NULL,
    [b12_master_ocean_bill_number]    NCHAR (16)    NULL,
    [b13_agency_unique_code]          NCHAR (5)     NULL,
    [b14_snp3]                        NCHAR (4)     NULL,
    [b15_snp4]                        NCHAR (4)     NULL,
    [b16_snp5]                        NCHAR (4)     NULL,
    [b17_snp6]                        NCHAR (4)     NULL,
    [b18_snp7]                        NCHAR (4)     NULL,
    [b19_snp8]                        NCHAR (4)     NULL,
    [b20_weight_unit]                 NCHAR (2)     NULL,
    [s1_shipper_name]                 NCHAR (35)    NULL,
    [s2_shipper_address1]             NCHAR (35)    NULL,
    [s3_shipper_address2]             NCHAR (35)    NULL,
    [s4_shipper_city]                 NCHAR (19)    NULL,
    [s5_shipper_state_province]       NCHAR (2)     NULL,
    [s6_shipper_postal_code]          NCHAR (10)    NULL,
    [s7_shipper_telephone_fax]        NCHAR (35)    NULL,
    [s8_shipper_iso_country_code]     NCHAR (2)     NULL,
    [s9_shipper_contact_name]         NCHAR (35)    NULL,
    [c1_consignee_name]               NCHAR (35)    NULL,
    [c2_consignee_address1]           NCHAR (35)    NULL,
    [c3_consignee_address2]           NCHAR (35)    NULL,
    [c4_consignee_city]               NCHAR (19)    NULL,
    [c5_consignee_state_province]     NCHAR (2)     NULL,
    [c6_consignee_postal_code]        NCHAR (9)     NULL,
    [c7_consignee_telephone_fax]      NCHAR (35)    NULL,
    [c8_consignee_iso_country_code]   NCHAR (2)     NULL,
    [c9_consignee_contact_name]       NCHAR (35)    NULL,
    [n1_notify_name]                  NCHAR (35)    NULL,
    [n2_notify_address1]              NCHAR (35)    NULL,
    [n3_notify_address2]              NCHAR (35)    NULL,
    [n4_notify_city]                  NCHAR (19)    NULL,
    [n5_notify_state_province]        NCHAR (2)     NULL,
    [n6_notify_postal_code]           NCHAR (9)     NULL,
    [n7_notify_telephone_fax]         NCHAR (35)    NULL,
    [n8_notify_iso_country_code]      NCHAR (2)     NULL,
    [n9_notify_party_contact_name]    NCHAR (35)    NULL
);

