CREATE TABLE [dbo].[iHAWB_master] (
    [elt_account_number]                  DECIMAL (8)     NOT NULL,
    [agent_elt_acct]                      DECIMAL (8)     NOT NULL,
    [tran_dt]                             DATETIME        NULL,
    [HAWB_NUM]                            NVARCHAR (32)   NULL,
    [MAWB_NUM]                            NVARCHAR (32)   NULL,
    [pieces]                              INT             NULL,
    [unit_qty]                            NVARCHAR (16)   NULL,
    [gross_wt]                            DECIMAL (12, 2) NULL,
    [chargeable_wt]                       DECIMAL (12, 2) NULL,
    [kg_lb]                               NCHAR (2)       NULL,
    [DEP_AIRPORT_CODE]                    NVARCHAR (3)    NULL,
    [airline_vendor_num]                  DECIMAL (5)     NULL,
    [Agent_Name]                          NVARCHAR (128)  NULL,
    [Agent_Info]                          NTEXT           NULL,
    [Agent_No]                            DECIMAL (7)     NULL,
    [Shipper_Name]                        NVARCHAR (128)  NULL,
    [Shipper_Info]                        NTEXT           NULL,
    [Shipper_account_number]              NVARCHAR (16)   NULL,
    [Consignee_Name]                      NVARCHAR (128)  NULL,
    [Consignee_Info]                      NTEXT           NULL,
    [Consignee_acct_num]                  NVARCHAR (32)   NULL,
    [Issue_Carrier_agent]                 NVARCHAR (128)  NULL,
    [Agent_IATA_Code]                     NVARCHAR (32)   NULL,
    [Account_No]                          NVARCHAR (32)   NULL,
    [Departure_Airport]                   NVARCHAR (32)   NULL,
    [departure_state]                     NVARCHAR (16)   NULL,
    [IssuedBy]                            NVARCHAR (128)  NULL,
    [Account_Info]                        NTEXT           NULL,
    [to_1]                                NVARCHAR (8)    NULL,
    [by_1]                                NVARCHAR (32)   NULL,
    [to_2]                                NVARCHAR (8)    NULL,
    [by_2]                                NVARCHAR (32)   NULL,
    [to_3]                                NVARCHAR (8)    NULL,
    [by_3]                                NVARCHAR (32)   NULL,
    [Currency]                            NVARCHAR (3)    NULL,
    [Charge_Code]                         NVARCHAR (2)    NULL,
    [PPO_1]                               NVARCHAR (1)    NULL,
    [COLL_1]                              NVARCHAR (1)    NULL,
    [PPO_2]                               NVARCHAR (1)    NULL,
    [COLL_2]                              NVARCHAR (1)    NULL,
    [Declared_Value_Carriage]             NVARCHAR (16)   NULL,
    [Declared_Value_Customs]              NVARCHAR (16)   NULL,
    [Dest_Airport]                        NVARCHAR (32)   NULL,
    [Flight_Date_1]                       NVARCHAR (10)   NULL,
    [Flight_Date_2]                       NVARCHAR (10)   NULL,
    [export_date]                         DATETIME        NULL,
    [Insurance_AMT]                       NVARCHAR (16)   NULL,
    [Handling_Info]                       NTEXT           NULL,
    [dest_country]                        NVARCHAR (32)   NULL,
    [SCI]                                 NVARCHAR (16)   NULL,
    [Total_Pieces]                        DECIMAL (4)     NULL,
    [Adjusted_Weight]                     DECIMAL (12, 2) NULL,
    [Total_Gross_Weight]                  DECIMAL (12, 2) NULL,
    [Total_Chargeable_Weight]             DECIMAL (12, 2) NULL,
    [Weight_Scale]                        NCHAR (1)       NULL,
    [Total_Weight_Charge_HAWB]            DECIMAL (12, 2) NULL,
    [Total_Weight_Charge_ACCT]            DECIMAL (12, 2) NULL,
    [Total_Other_Charges]                 DECIMAL (12, 2) NULL,
    [Prepaid_Weight_Charge]               DECIMAL (12, 2) NULL,
    [Collect_Weight_Charge]               DECIMAL (12, 2) NULL,
    [Prepaid_Valuation_Charge]            DECIMAL (12, 2) NULL,
    [Collect_Valuation_Charge]            DECIMAL (12, 2) NULL,
    [Prepaid_Tax]                         DECIMAL (12, 2) NULL,
    [Collect_Tax]                         DECIMAL (12, 2) NULL,
    [Prepaid_Due_Agent]                   DECIMAL (12, 2) NULL,
    [Collect_Due_Agent]                   DECIMAL (12, 2) NULL,
    [Prepaid_Due_Carrier]                 DECIMAL (12, 2) NULL,
    [Collect_Due_Carrier]                 DECIMAL (12, 2) NULL,
    [Prepaid_Unused]                      DECIMAL (12, 2) NULL,
    [Collect_Unused]                      DECIMAL (12, 2) NULL,
    [Prepaid_Total]                       DECIMAL (12, 2) NULL,
    [Collect_Total]                       DECIMAL (12, 2) NULL,
    [Signature]                           NVARCHAR (64)   NULL,
    [Date_Executed]                       DATETIME        NULL,
    [Execution]                           NVARCHAR (256)  NULL,
    [Date_Last_Modified]                  DATETIME        NULL,
    [Currency_Conv_Rate]                  DECIMAL (10, 2) NULL,
    [CC_Charge_Dest_Rate]                 DECIMAL (10, 2) NULL,
    [Charge_at_Dest]                      DECIMAL (12, 2) NULL,
    [Total_Collect_Charge]                DECIMAL (12, 2) NULL,
    [Desc1]                               NTEXT           NULL,
    [Desc2]                               NTEXT           NULL,
    [manifest_desc]                       NVARCHAR (128)  NULL,
    [Show_Weight_Charge_Shipper]          NCHAR (1)       NULL,
    [Show_Weight_Charge_Consignee]        NCHAR (1)       NULL,
    [Show_Prepaid_Other_Charge_Shipper]   NCHAR (1)       NULL,
    [Show_Collect_Other_Charge_Shipper]   NCHAR (1)       NULL,
    [Show_Prepaid_Other_Charge_Consignee] NCHAR (1)       NULL,
    [Show_Collect_Other_Charge_Consignee] NCHAR (1)       NULL,
    [Prepaid_Invoiced]                    NCHAR (1)       NULL,
    [Collect_Invoiced]                    NCHAR (1)       NULL,
    [agent_bbk]                           DECIMAL (12, 2) CONSTRAINT [DF_iHAWB_master_agent_bbk] DEFAULT (0) NULL,
    [agent_profit_share]                  DECIMAL (12, 2) CONSTRAINT [DF_iHAWB_master_agent_profit_share] DEFAULT (0) NULL,
    [agent_others]                        DECIMAL (12, 2) CONSTRAINT [DF_iHAWB_master_agent_others] DEFAULT (0) NULL,
    [ref_no]                              NVARCHAR (32)   NULL,
    [sub_master]                          NVARCHAR (32)   NULL,
    [it_no]                               NVARCHAR (32)   NULL,
    [it_date]                             NVARCHAR (32)   NULL,
    [mfst_no]                             NVARCHAR (32)   NULL,
    [entry_no]                            NVARCHAR (32)   NULL,
    [freight_location]                    NVARCHAR (64)   NULL,
    [storage_begin]                       NVARCHAR (32)   NULL
);

