CREATE TABLE [dbo].[ihbol_master] (
    [elt_account_number]         DECIMAL (8)     NULL,
    [hbol_num]                   NVARCHAR (24)   NULL,
    [booking_num]                NVARCHAR (32)   NULL,
    [mbol_num]                   NVARCHAR (32)   NULL,
    [agent_name]                 NVARCHAR (128)  NULL,
    [agent_info]                 NTEXT           NULL,
    [agent_no]                   DECIMAL (6)     NULL,
    [forward_agent_name]         NVARCHAR (128)  NULL,
    [forward_agent_info]         NTEXT           NULL,
    [forward_agent_acct_num]     DECIMAL (7)     NULL,
    [Shipper_Name]               NVARCHAR (128)  NULL,
    [Shipper_Info]               NTEXT           NULL,
    [Shipper_acct_num]           DECIMAL (7)     NULL,
    [Consignee_Name]             NVARCHAR (128)  NULL,
    [Consignee_Info]             NTEXT           NULL,
    [Consignee_acct_num]         DECIMAL (7)     NULL,
    [export_ref]                 NTEXT           NULL,
    [notify_info]                NTEXT           NULL,
    [origin_country]             NVARCHAR (32)   NULL,
    [export_instr]               NTEXT           NULL,
    [loading_pier]               NVARCHAR (32)   NULL,
    [move_type]                  NVARCHAR (32)   NULL,
    [containerized]              NCHAR (1)       NULL,
    [pre_carriage]               NVARCHAR (32)   NULL,
    [pre_receipt_place]          NVARCHAR (32)   NULL,
    [export_carrier]             NVARCHAR (32)   NULL,
    [loading_port]               NVARCHAR (64)   NULL,
    [unloading_port]             NVARCHAR (64)   NULL,
    [departure_date]             DATETIME        NULL,
    [delivery_place]             NVARCHAR (32)   NULL,
    [desc1]                      NTEXT           NULL,
    [desc2]                      NTEXT           NULL,
    [desc3]                      NTEXT           NULL,
    [desc6]                      NTEXT           NULL,
    [desc5]                      NTEXT           NULL,
    [weight_cp]                  NCHAR (1)       NULL,
    [prepaid_other_charge]       NCHAR (1)       NULL,
    [collect_other_charge]       NCHAR (1)       NULL,
    [pieces]                     INT             NULL,
    [scale]                      NCHAR (1)       NULL,
    [gross_weight]               DECIMAL (12, 2) NULL,
    [measurement]                DECIMAL (12, 2) NULL,
    [width]                      DECIMAL (10, 2) NULL,
    [length]                     DECIMAL (10, 2) NULL,
    [height]                     DECIMAL (10, 2) NULL,
    [dem_detail]                 NTEXT           NULL,
    [charge_rate]                FLOAT (53)      NULL,
    [total_weight_charge]        DECIMAL (12, 2) NULL,
    [Show_Prepaid_Weight_Charge] NCHAR (1)       NULL,
    [Show_Collect_Weight_Charge] NCHAR (1)       NULL,
    [Show_Prepaid_Other_Charge]  NCHAR (1)       NULL,
    [Show_Collect_Other_Charge]  NCHAR (1)       NULL,
    [declared_value]             DECIMAL (12, 2) NULL,
    [tran_by]                    NVARCHAR (64)   NULL,
    [tran_date]                  DATETIME        NULL,
    [tran_place]                 NVARCHAR (32)   NULL,
    [last_modified]              DATETIME        NULL,
    [agent_bbk]                  DECIMAL (12, 2) CONSTRAINT [DF_ihbol_master_agent_bbk] DEFAULT (0) NULL,
    [agent_profit_share]         DECIMAL (12, 2) CONSTRAINT [DF_ihbol_master_agent_profit_share] DEFAULT (0) NULL,
    [agent_others]               DECIMAL (12, 2) CONSTRAINT [DF_ihbol_master_agent_others] DEFAULT (0) NULL,
    [ref_no]                     NVARCHAR (32)   NULL,
    [sub_master]                 NVARCHAR (32)   NULL,
    [it_no]                      NVARCHAR (32)   NULL,
    [it_date]                    NVARCHAR (32)   NULL,
    [mfst_no]                    NVARCHAR (32)   NULL,
    [entry_no]                   NVARCHAR (32)   NULL,
    [freight_location]           NVARCHAR (64)   NULL,
    [storage_begin]              NVARCHAR (32)   NULL,
    [f_port1]                    NVARCHAR (32)   NULL,
    [f_eta1]                     NVARCHAR (32)   NULL,
    [f_port2]                    NVARCHAR (32)   NULL,
    [f_eta2]                     NVARCHAR (32)   NULL,
    [f_port3]                    NVARCHAR (32)   NULL,
    [f_eta3]                     NVARCHAR (32)   NULL,
    [container]                  NVARCHAR (32)   NULL,
    [prepaid_invoiced]           NCHAR (1)       CONSTRAINT [DF_ihbol_master_prepaid_invoiced] DEFAULT ('N') NULL,
    [collect_invoiced]           NCHAR (1)       CONSTRAINT [DF_ihbol_master_collect_invoiced] DEFAULT ('N') NULL
);

