CREATE TABLE [dbo].[iMAWB_NUMBER] (
    [elt_account_number]   DECIMAL (8)   NOT NULL,
    [mawb_no]              NVARCHAR (32) NOT NULL,
    [Carrier_Code]         NVARCHAR (16) NULL,
    [Carrier_Desc]         NVARCHAR (32) NULL,
    [Flight#]              NVARCHAR (8)  NULL,
    [File#]                NVARCHAR (32) NULL,
    [Created_Date]         DATETIME      NULL,
    [Origin_Port_ID]       NVARCHAR (3)  NULL,
    [Origin_Port_Location] NVARCHAR (32) NULL,
    [Origin_Port_State]    NVARCHAR (8)  NULL,
    [Origin_Port_Country]  NVARCHAR (32) NULL,
    [Dest_Port_ID]         NVARCHAR (3)  NULL,
    [Dest_Port_Location]   NVARCHAR (32) NULL,
    [Dest_Port_Country]    NVARCHAR (32) NULL,
    [To]                   NVARCHAR (3)  NULL,
    [By]                   NVARCHAR (32) NULL,
    [To_1]                 NVARCHAR (3)  NULL,
    [By_1]                 NVARCHAR (17) NULL,
    [To_2]                 NVARCHAR (3)  NULL,
    [By_2]                 NVARCHAR (17) NULL,
    [Flight#1]             NVARCHAR (32) NULL,
    [Flight#2]             NVARCHAR (32) NULL,
    [ETD_DATE1]            DATETIME      NULL,
    [ETD_DATE2]            DATETIME      NULL,
    [ETA_DATE1]            DATETIME      NULL,
    [ETA_DATE2]            DATETIME      NULL,
    [Weight_Reserved]      DECIMAL (18)  NULL,
    [Weight_Scale]         NVARCHAR (4)  NULL,
    [Status]               NCHAR (1)     NULL
);

