CREATE TABLE [dbo].[import_hawb] (
    [elt_account_number] DECIMAL (8)     NOT NULL,
    [agent_elt_acct]     DECIMAL (8)     NULL,
    [agent_org_acct]     DECIMAL (8)     NULL,
    [tran_dt]            DATETIME        NULL,
    [iType]              NCHAR (1)       NULL,
    [mawb_num]           NVARCHAR (32)   NULL,
    [hawb_num]           NVARCHAR (32)   NOT NULL,
    [sec]                INT             NOT NULL,
    [invoice_no]         DECIMAL (12)    CONSTRAINT [DF_import_hawb_invoice_no] DEFAULT (0) NULL,
    [process_dt]         DATETIME        NULL,
    [processed]          NCHAR (1)       NULL,
    [shipper_name]       NVARCHAR (128)  NULL,
    [shipper_info]       NTEXT           NULL,
    [shipper_acct]       DECIMAL (8)     CONSTRAINT [DF_import_hawb_shipper_acct] DEFAULT (0) NULL,
    [consignee_name]     NVARCHAR (128)  NULL,
    [consignee_info]     NTEXT           NULL,
    [consignee_acct]     DECIMAL (8)     CONSTRAINT [DF_import_hawb_consignee_acct] DEFAULT (0) NULL,
    [notify_name]        NVARCHAR (128)  NULL,
    [notify_info]        NTEXT           NULL,
    [notify_acct]        DECIMAL (8)     CONSTRAINT [DF_import_hawb_notify_acct] DEFAULT (0) NULL,
    [broker_info]        NTEXT           NULL,
    [broker_acct]        DECIMAL (8)     CONSTRAINT [DF_import_hawb_broker_acct] DEFAULT (0) NULL,
    [pieces]             DECIMAL (18)    CONSTRAINT [DF_import_hawb_pieces] DEFAULT (0) NULL,
    [uom]                NVARCHAR (16)   NULL,
    [gross_wt]           DECIMAL (12, 2) CONSTRAINT [DF_import_hawb_gross_wt] DEFAULT (0) NULL,
    [scale1]             NCHAR (3)       NULL,
    [chg_wt]             DECIMAL (12, 2) CONSTRAINT [DF_import_hawb_chg_wt] DEFAULT (0) NULL,
    [scale2]             NCHAR (3)       NULL,
    [prepaid_collect]    NCHAR (1)       NULL,
    [freight_collect]    DECIMAL (12, 2) CONSTRAINT [DF_import_hawb_freight_collect] DEFAULT (0) NULL,
    [oc_collect]         DECIMAL (12, 2) CONSTRAINT [DF_import_hawb_oc_collect] DEFAULT (0) NULL,
    [prepared_by]        NVARCHAR (64)   NULL,
    [sub_mawb1]          NVARCHAR (32)   NULL,
    [sub_mawb2]          NVARCHAR (32)   NULL,
    [customer_ref]       NVARCHAR (64)   NULL,
    [delivery_place]     NVARCHAR (64)   NULL,
    [etd2]               NVARCHAR (32)   NULL,
    [eta2]               NVARCHAR (32)   NULL,
    [container_location] NVARCHAR (256)  NULL,
    [destination]        NVARCHAR (256)  NULL,
    [free_date]          NVARCHAR (32)   NULL,
    [go_date]            NVARCHAR (32)   NULL,
    [it_number]          NVARCHAR (64)   NULL,
    [it_date]            NVARCHAR (64)   NULL,
    [it_entry_port]      NVARCHAR (64)   NULL,
    [cargo_location]     NVARCHAR (128)  NULL,
    [desc1]              NTEXT           NULL,
    [desc2]              NTEXT           NULL,
    [desc3]              NTEXT           NULL,
    [desc4]              NTEXT           NULL,
    [desc5]              NTEXT           NULL,
    [remarks]            NTEXT           NULL,
    [term]               INT             NULL,
    [pickup_date]        DATETIME        NULL,
    [igSub_HAWB]         NVARCHAR (32)   NULL,
    [SalesPerson]        NVARCHAR (64)   NULL,
    [CreatedBy]          NVARCHAR (64)   NULL,
    [CreatedDate]        DATETIME        NULL,
    [ModifiedBy]         NVARCHAR (64)   NULL,
    [ModifiedDate]       DATETIME        NULL,
    [fc_rate]            DECIMAL (12, 3) NULL,
    [fc_charge]          DECIMAL (12, 3) NULL,
    [total_other_charge] DECIMAL (12)    NULL,
    [dep_code]           NVARCHAR (8)    NULL,
    [arr_code]           NVARCHAR (8)    NULL,
    [is_default_rate]    NCHAR (1)       NULL,
    [eta]                NVARCHAR (32)   NULL,
    [etd]                NVARCHAR (32)   NULL,
    [flt_no]             NVARCHAR (32)   NULL,
    [broker_name]        NVARCHAR (128)  NULL,
    [is_org_merged]      NCHAR (1)       NULL,
    [dep_port]           NVARCHAR (128)  NULL,
    [arr_port]           NVARCHAR (128)  NULL,
    [carrier_code]       NVARCHAR (16)   NULL
);

