CREATE TABLE [dbo].[invoice_joined_temp] (
    [invoice_id]          INT             NOT NULL,
    [customer_dba_name]   NVARCHAR (180)  NULL,
    [business_phone]      NVARCHAR (32)   NULL,
    [customer_credit]     INT             NULL,
    [customer_no]         NVARCHAR (32)   NULL,
    [elt_account_number]  DECIMAL (8)     NOT NULL,
    [invoice_no]          DECIMAL (12)    NOT NULL,
    [invoice_type]        NCHAR (1)       NULL,
    [import_export]       NVARCHAR (1)    NULL,
    [air_ocean]           NVARCHAR (1)    NULL,
    [invoice_date]        DATETIME        NULL,
    [ref_no]              NVARCHAR (64)   NULL,
    [ref_no_our]          NVARCHAR (64)   NULL,
    [customer_info]       NVARCHAR (512)  NULL,
    [total_pieces]        NVARCHAR (32)   NULL,
    [total_gross_weight]  NVARCHAR (32)   NULL,
    [total_charge_weight] NVARCHAR (32)   NULL,
    [origin_dest]         NVARCHAR (64)   NULL,
    [origin]              NVARCHAR (64)   NULL,
    [dest]                NVARCHAR (64)   NULL,
    [customer_number]     NVARCHAR (32)   NULL,
    [customer_name]       NVARCHAR (128)  NULL,
    [shipper]             NVARCHAR (512)  NULL,
    [consignee]           NVARCHAR (512)  NULL,
    [entry_no]            NVARCHAR (32)   NULL,
    [entry_date]          DATETIME        NULL,
    [carrier]             NVARCHAR (128)  NULL,
    [arrival_dept]        NVARCHAR (32)   NULL,
    [mawb_num]            NVARCHAR (64)   NULL,
    [hawb_num]            NVARCHAR (64)   NULL,
    [subtotal]            DECIMAL (12, 2) NULL,
    [sale_tax]            DECIMAL (12, 2) NULL,
    [agent_profit]        DECIMAL (12, 2) NULL,
    [accounts_receivable] DECIMAL (5)     NULL,
    [amount_charged]      DECIMAL (12, 2) NULL,
    [amount_paid]         DECIMAL (12, 2) NULL,
    [balance]             DECIMAL (12, 2) NULL,
    [total_cost]          DECIMAL (12, 2) NULL,
    [remarks]             NTEXT           NULL,
    [pay_status]          NCHAR (1)       NULL,
    [term_curr]           INT             NULL,
    [term30]              NCHAR (1)       NULL,
    [term60]              NCHAR (1)       NULL,
    [term90]              NCHAR (1)       NULL,
    [received_amt]        DECIMAL (9, 2)  NULL,
    [pmt_method]          NVARCHAR (16)   NULL,
    [existing_credits]    DECIMAL (9, 2)  NULL,
    [deposit_to]          DECIMAL (9)     NULL,
    [lock_ar]             NCHAR (1)       NULL,
    [lock_ap]             NCHAR (1)       NULL,
    [in_memo]             NTEXT           NULL,
    [is_org_merged]       NCHAR (1)       NULL,
    [master_invoice_no]   DECIMAL (18)    NULL
);

