CREATE TABLE [dbo].[MAWB_MASTER] (
    [elt_account_number]                  DECIMAL (8)     NOT NULL,
    [MAWB_NUM]                            NVARCHAR (64)   NULL,
    [DEP_AIRPORT_CODE]                    NVARCHAR (3)    NULL,
    [master_agent]                        DECIMAL (5)     NULL,
    [airline_vendor_num]                  DECIMAL (5)     NULL,
    [Shipper_Name]                        NVARCHAR (128)  NULL,
    [Shipper_Info]                        NTEXT           NULL,
    [Shipper_account_number]              NVARCHAR (16)   NULL,
    [ff_shipper_acct]                     NVARCHAR (64)   NULL,
    [Consignee_Name]                      NVARCHAR (256)  NULL,
    [Consignee_Info]                      NTEXT           NULL,
    [Consignee_acct_num]                  NVARCHAR (32)   NULL,
    [ff_consignee_acct]                   NVARCHAR (64)   NULL,
    [Issue_Carrier_agent]                 NTEXT           NULL,
    [Agent_IATA_Code]                     NVARCHAR (32)   NULL,
    [Account_No]                          NVARCHAR (32)   NULL,
    [Departure_Airport]                   NVARCHAR (64)   NULL,
    [IssuedBy]                            NTEXT           NULL,
    [Account_Info]                        NTEXT           NULL,
    [to_1]                                NVARCHAR (8)    NULL,
    [by_1]                                NVARCHAR (64)   NULL,
    [to_2]                                NVARCHAR (8)    NULL,
    [by_2]                                NVARCHAR (64)   NULL,
    [to_3]                                NVARCHAR (8)    NULL,
    [by_3]                                NVARCHAR (64)   NULL,
    [Currency]                            NVARCHAR (3)    NULL,
    [Charge_Code]                         NVARCHAR (10)   NULL,
    [PPO_1]                               NVARCHAR (1)    NULL,
    [COLL_1]                              NVARCHAR (1)    NULL,
    [PPO_2]                               NVARCHAR (1)    NULL,
    [COLL_2]                              NVARCHAR (1)    NULL,
    [Declared_Value_Carriage]             NVARCHAR (16)   NULL,
    [Declared_Value_Customs]              NVARCHAR (16)   NULL,
    [Dest_Airport]                        NVARCHAR (64)   NULL,
    [Flight_Date_1]                       NVARCHAR (32)   NULL,
    [Flight_Date_2]                       NVARCHAR (32)   NULL,
    [Insurance_AMT]                       NVARCHAR (16)   NULL,
    [Handling_Info]                       NTEXT           NULL,
    [dest_country]                        NVARCHAR (32)   NULL,
    [SCI]                                 NVARCHAR (16)   NULL,
    [Total_Pieces]                        DECIMAL (4)     NULL,
    [Adjusted_Weight]                     DECIMAL (12, 2) NULL,
    [Total_Gross_Weight]                  DECIMAL (12, 2) NULL,
    [total_chargeable_weight]             DECIMAL (12, 2) CONSTRAINT [DF_MAWB_MASTER_total_chargeable_weight] DEFAULT (0) NULL,
    [Weight_Scale]                        NCHAR (1)       NULL,
    [Total_Weight_Charge_HAWB]            DECIMAL (12, 2) NULL,
    [Total_Weight_Charge_ACCT]            DECIMAL (12, 2) NULL,
    [Total_Other_Charges]                 DECIMAL (12, 2) NULL,
    [total_other_cost]                    DECIMAL (18, 2) NULL,
    [Prepaid_Weight_Charge]               DECIMAL (12, 2) NULL,
    [Collect_Weight_Charge]               DECIMAL (12, 2) NULL,
    [Prepaid_Valuation_Charge]            DECIMAL (12, 2) NULL,
    [Collect_Valuation_Charge]            DECIMAL (12, 2) NULL,
    [Prepaid_Tax]                         DECIMAL (12, 2) NULL,
    [Collect_Tax]                         DECIMAL (12, 2) NULL,
    [Prepaid_Due_Agent]                   DECIMAL (12, 2) NULL,
    [Collect_Due_Agent]                   DECIMAL (12, 2) NULL,
    [Prepaid_Due_Carrier]                 DECIMAL (12, 2) NULL,
    [Collect_Due_Carrier]                 DECIMAL (12, 2) NULL,
    [Prepaid_Unused]                      DECIMAL (12, 2) NULL,
    [Collect_Unused]                      DECIMAL (12, 2) NULL,
    [Prepaid_Total]                       DECIMAL (12, 2) NULL,
    [Collect_Total]                       DECIMAL (12, 2) NULL,
    [Signature]                           NTEXT           NULL,
    [Date_Executed]                       DATETIME        NULL,
    [Place_Executed]                      NVARCHAR (64)   NULL,
    [Execution]                           NTEXT           NULL,
    [Date_Last_Modified]                  DATETIME        NULL,
    [Currency_Conv_Rate]                  DECIMAL (10, 2) NULL,
    [CC_Charge_Dest_Rate]                 DECIMAL (10, 2) NULL,
    [Charge_at_Dest]                      DECIMAL (12, 2) NULL,
    [Total_Collect_Charge]                DECIMAL (12, 2) NULL,
    [Desc1]                               NTEXT           NULL,
    [Desc2]                               NTEXT           NULL,
    [Show_Weight_Charge_Shipper]          NCHAR (1)       CONSTRAINT [DF_MAWB_MASTER_Show_Weight_Charge_Shipper] DEFAULT ('Y') NULL,
    [Show_Weight_Charge_Consignee]        NCHAR (1)       CONSTRAINT [DF_MAWB_MASTER_Show_Weight_Charge_Consignee] DEFAULT ('Y') NULL,
    [Show_Prepaid_Other_Charge_Shipper]   NCHAR (1)       CONSTRAINT [DF_MAWB_MASTER_Show_Prepaid_Other_Charge_Shipper] DEFAULT ('Y') NULL,
    [Show_Collect_Other_Charge_Shipper]   NCHAR (1)       CONSTRAINT [DF_MAWB_MASTER_Show_Collect_Other_Charge_Shipper] DEFAULT ('Y') NULL,
    [Show_Prepaid_Other_Charge_Consignee] NCHAR (1)       CONSTRAINT [DF_MAWB_MASTER_Show_Prepaid_Other_Charge_Consignee] DEFAULT ('Y') NULL,
    [Show_Collect_Other_Charge_Consignee] NCHAR (1)       CONSTRAINT [DF_MAWB_MASTER_Show_Collect_Other_Charge_Consignee] DEFAULT ('Y') NULL,
    [Invoiced]                            NCHAR (1)       NULL,
    [Notify_no]                           NVARCHAR (32)   NULL,
    [SalesPerson]                         NVARCHAR (64)   NULL,
    [CreatedBy]                           NVARCHAR (64)   NULL,
    [CreatedDate]                         DATETIME        NULL,
    [ModifiedBy]                          NVARCHAR (64)   NULL,
    [ModifiedDate]                        DATETIME        NULL,
    [is_org_merged]                       NCHAR (1)       NULL,
    [dimtext]                             NTEXT           NULL,
    [reference_number]                    NVARCHAR (32)   NULL,
    [is_dome]                             NVARCHAR (1)    CONSTRAINT [DF__mawb_mast__is_do__25FB978D] DEFAULT ('N') NOT NULL,
    [master_type]                         NVARCHAR (2)    NULL,
    [bill_to_party]                       NVARCHAR (1)    NULL,
    [service_level_other]                 NVARCHAR (64)   NULL,
    [iac_num]                             NVARCHAR (64)   NULL,
    [known_shipper]                       NVARCHAR (128)  NULL,
    [unknown_shipper]                     NVARCHAR (128)  NULL,
    [item_under_16]                       NVARCHAR (128)  NULL,
    [shipper_reference_num]               NVARCHAR (64)   NULL,
    [carrier_icc_num]                     NVARCHAR (64)   NULL,
    [dim_text]                            NVARCHAR (128)  NULL,
    [shipper_COD]                         DECIMAL (10, 2) NULL,
    [third_party_no]                      NVARCHAR (64)   NULL,
    [is_inbound]                          NVARCHAR (1)    CONSTRAINT [DF__mawb_mast__is_in__597B3B93] DEFAULT ('N') NULL,
    [service_level]                       NVARCHAR (64)   NULL,
    [cod_amount]                          DECIMAL (10, 2) NULL,
    [pickup_charge]                       DECIMAL (10, 2) NULL,
    [origin_adv_charge]                   DECIMAL (10, 2) NULL,
    [origin_adv_charge_desc]              NVARCHAR (128)  NULL,
    [dest_adv_charge]                     DECIMAL (10, 2) NULL,
    [dest_adv_charge_desc]                NVARCHAR (128)  NULL,
    [item_prepaid]                        DECIMAL (10, 2) NULL,
    [item_collect]                        DECIMAL (10, 2) NULL,
    [cod_fee]                             DECIMAL (10, 2) NULL,
    [other_charge]                        DECIMAL (10, 2) NULL,
    [delivery_charge]                     DECIMAL (10, 2) NULL,
    [Total_Freight_Cost]                  DECIMAL (12, 2) NULL,
    [aes_xtn]                             NVARCHAR (64)   NULL,
    [sed_stmt]                            NVARCHAR (128)  NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [PK_mawb_master]
    ON [dbo].[MAWB_MASTER]([elt_account_number] ASC, [MAWB_NUM] ASC);


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-MAWB_MASTER]
    ON [dbo].[MAWB_MASTER]([MAWB_NUM] ASC)
    INCLUDE([elt_account_number], [DEP_AIRPORT_CODE], [airline_vendor_num], [to_1], [PPO_1], [COLL_1], [Date_Last_Modified]);

