CREATE TABLE [dbo].[organization] (
    [elt_account_number]       DECIMAL (8)     NOT NULL,
    [org_account_number]       DECIMAL (18)    NOT NULL,
    [dba_name]                 NVARCHAR (128)  NULL,
    [class_code]               NCHAR (32)      NULL,
    [isFrequently]             NCHAR (1)       NULL,
    [business_legal_name]      NTEXT           NULL,
    [business_fed_taxid]       NVARCHAR (16)   NULL,
    [business_address]         NTEXT           NULL,
    [business_address2]        NTEXT           NULL,
    [business_address3]        NTEXT           NULL,
    [business_city]            NVARCHAR (128)  NULL,
    [business_state]           NVARCHAR (64)   NULL,
    [business_zip]             NVARCHAR (32)   NULL,
    [business_country]         NVARCHAR (64)   NULL,
    [b_country_code]           NVARCHAR (2)    NULL,
    [business_phone]           NVARCHAR (32)   NULL,
    [business_phone_ext]       NVARCHAR (16)   NULL,
    [business_phone_mask]      NCHAR (2)       NULL,
    [business_phone2]          NVARCHAR (32)   NULL,
    [business_phone2_ext]      NVARCHAR (16)   NULL,
    [business_phone2_mask]     NCHAR (2)       NULL,
    [business_fax]             NVARCHAR (32)   NULL,
    [business_fax_mask]        NCHAR (2)       NULL,
    [business_url]             NVARCHAR (64)   NULL,
    [web_login_id]             NVARCHAR (32)   NULL,
    [web_login_pin]            NVARCHAR (32)   NULL,
    [owner_lname]              NVARCHAR (32)   NULL,
    [owner_fname]              NVARCHAR (32)   NULL,
    [owner_mname]              NVARCHAR (32)   NULL,
    [owner_title]              NTEXT           NULL,
    [owner_departm]            NTEXT           NULL,
    [owner_mail_address]       NTEXT           NULL,
    [owner_mail_address2]      NTEXT           NULL,
    [owner_mail_address3]      NTEXT           NULL,
    [owner_mail_city]          NVARCHAR (32)   NULL,
    [owner_mail_state]         NVARCHAR (32)   NULL,
    [owner_mail_zip]           NVARCHAR (32)   NULL,
    [owner_mail_country]       NVARCHAR (64)   NULL,
    [owner_phone]              NVARCHAR (32)   NULL,
    [owner_phone_mask]         NCHAR (2)       NULL,
    [owner_email]              NVARCHAR (1024) NULL,
    [attn_name]                NVARCHAR (64)   NULL,
    [notify_name]              NVARCHAR (64)   NULL,
    [agent_elt_acct]           NCHAR (8)       NULL,
    [edt]                      NCHAR (1)       NULL,
    [iata_code]                NVARCHAR (16)   NULL,
    [carrier_code]             NVARCHAR (16)   NULL,
    [carrier_id]               NVARCHAR (16)   NULL,
    [carrier_type]             NCHAR (1)       NULL,
    [account_status]           NVARCHAR (1)    NULL,
    [comment]                  NTEXT           NULL,
    [comment2]                 NTEXT           NULL,
    [credit_amt]               DECIMAL (12, 2) NULL,
    [bill_term]                INT             NULL,
    [coloader_elt_acct]        DECIMAL (8)     NULL,
    [colodee_elt_acct_name]    NTEXT           NULL,
    [z_bond_number]            DECIMAL (18)    NULL,
    [z_bond_exp_date]          DATETIME        NULL,
    [z_bond_amount]            DECIMAL (18)    NULL,
    [z_bond_surety]            NTEXT           NULL,
    [z_bank_name]              NTEXT           NULL,
    [z_bank_account_no]        NCHAR (20)      NULL,
    [z_chl_no]                 NVARCHAR (30)   NULL,
    [z_firm_code]              NVARCHAR (30)   NULL,
    [z_carrier_code]           NVARCHAR (30)   NULL,
    [z_carrier_prefix]         NCHAR (10)      NULL,
    [z_attn_txt]               NVARCHAR (64)   NULL,
    [SalesPerson]              NVARCHAR (32)   NULL,
    [c2FirstName]              NVARCHAR (32)   NULL,
    [c2MiddleName]             NVARCHAR (32)   NULL,
    [c2LastName]               NVARCHAR (32)   NULL,
    [c2Title]                  NTEXT           NULL,
    [c2Phone]                  NVARCHAR (32)   NULL,
    [c2Ext]                    NVARCHAR (16)   NULL,
    [c2Phone_mask]             NCHAR (2)       NULL,
    [c2Cell]                   NVARCHAR (32)   NULL,
    [c2Cell_mask]              NCHAR (2)       NULL,
    [c2Fax]                    NVARCHAR (32)   NULL,
    [c2Fax_mask]               NCHAR (2)       NULL,
    [c2Email]                  NTEXT           NULL,
    [c3FirstName]              NVARCHAR (32)   NULL,
    [c3MiddleName]             NVARCHAR (32)   NULL,
    [c3LastName]               NVARCHAR (32)   NULL,
    [c3Title]                  NTEXT           NULL,
    [c3Phone]                  NVARCHAR (32)   NULL,
    [c3Phone_mask]             NCHAR (2)       NULL,
    [c3Ext]                    NVARCHAR (16)   NULL,
    [c3Cell]                   NVARCHAR (32)   NULL,
    [c3Cell_mask]              NCHAR (2)       NULL,
    [c3Fax]                    NVARCHAR (32)   NULL,
    [c3Fax_mask]               NCHAR (2)       NULL,
    [c3Email]                  NTEXT           NULL,
    [is_shipper]               NCHAR (1)       NULL,
    [is_consignee]             NCHAR (1)       NULL,
    [is_agent]                 NCHAR (1)       NULL,
    [is_vendor]                NCHAR (1)       NULL,
    [is_carrier]               NCHAR (1)       NULL,
    [is_coloader]              NCHAR (1)       CONSTRAINT [DF_organization_is_colodee] DEFAULT ('N') NULL,
    [z_is_trucker]             NCHAR (1)       NULL,
    [z_is_special]             NCHAR (1)       NULL,
    [z_is_broker]              NCHAR (1)       NULL,
    [z_is_warehousing]         NCHAR (1)       NULL,
    [z_is_cfs]                 NCHAR (1)       NULL,
    [z_is_govt]                NCHAR (1)       NULL,
    [SubConsignee]             NVARCHAR (32)   NULL,
    [SubShipper]               NVARCHAR (32)   NULL,
    [SubAgent]                 NVARCHAR (32)   NULL,
    [SubCarrier]               NVARCHAR (32)   NULL,
    [SubTrucker]               NVARCHAR (32)   NULL,
    [SubWarehousing]           NVARCHAR (32)   NULL,
    [SubCFS]                   NVARCHAR (32)   NULL,
    [SubBroker]                NVARCHAR (32)   NULL,
    [SubGovt]                  NVARCHAR (32)   NULL,
    [SubVendor]                NVARCHAR (32)   NULL,
    [SubSpecial]               NVARCHAR (32)   NULL,
    [defaultBroker]            NVARCHAR (20)   NULL,
    [defaultBrokerName]        NVARCHAR (128)  NULL,
    [broker_info]              NTEXT           NULL,
    [refferedBy]               NVARCHAR (64)   NULL,
    [date_opened]              DATETIME        NULL,
    [last_update]              DATETIME        NULL,
    [acct_name]                NVARCHAR (16)   NULL,
    [business_st_taxid]        NVARCHAR (16)   NULL,
    [owner_ssn]                NVARCHAR (10)   NULL,
    [business_phone_mask_exp]  NTEXT           NULL,
    [business_phone2_mask_exp] NTEXT           NULL,
    [business_fax_mask_exp]    NTEXT           NULL,
    [owner_phone_mask_exp]     NTEXT           NULL,
    [c2Phone_mask_exp]         NTEXT           NULL,
    [c2Cell_mask_exp]          NTEXT           NULL,
    [c2Fax_mask_exp]           NTEXT           NULL,
    [c3Phone_mask_exp]         NTEXT           NULL,
    [c3Cell_mask_exp]          NTEXT           NULL,
    [c3Fax_mask_exp]           NTEXT           NULL,
    [business_phone_mask_pre]  NCHAR (10)      NULL,
    [business_phone2_mask_pre] NCHAR (10)      NULL,
    [business_fax_mask_pre]    NCHAR (10)      NULL,
    [owner_phone_mask_pre]     NCHAR (10)      NULL,
    [c2Phone_mask_pre]         NCHAR (10)      NULL,
    [c2Cell_mask_pre]          NCHAR (10)      NULL,
    [c2Fax_mask_pre]           NCHAR (10)      NULL,
    [c3Phone_mask_pre]         NCHAR (10)      NULL,
    [c3Cell_mask_pre]          NCHAR (10)      NULL,
    [c3Fax_mask_pre]           NCHAR (10)      NULL,
    [print_check_as]           NTEXT           NULL,
    [print_check_as_info]      NTEXT           NULL,
    [known_shipper]            NCHAR (1)       NULL,
    [coloader_elt_acct_name]   NTEXT           NULL,
    [ICC_MC]                   NVARCHAR (64)   NULL,
    [FF_account_no]            NVARCHAR (64)   NULL,
    [is_customer]              NVARCHAR (1)    NULL,
    [subCustomer]              NVARCHAR (32)   NULL,
    [OrgId]                    INT             IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_organization] PRIMARY KEY CLUSTERED ([elt_account_number] ASC, [org_account_number] ASC)
);


GO
CREATE NONCLUSTERED INDEX [org]
    ON [dbo].[organization]([elt_account_number] ASC, [org_account_number] ASC);


GO
CREATE NONCLUSTERED INDEX [org_dba]
    ON [dbo].[organization]([elt_account_number] ASC, [dba_name] ASC);


GO
CREATE NONCLUSTERED INDEX [carrier_code]
    ON [dbo].[organization]([elt_account_number] ASC, [carrier_code] ASC, [dba_name] ASC);

