CREATE TABLE [dbo].[tmp_org] (
    [elt_account_number] DECIMAL (18)   NULL,
    [org_account_number] DECIMAL (7)    NOT NULL,
    [dba_name]           NVARCHAR (128) NULL,
    [class_code]         NCHAR (20)     NULL,
    [isFrequently]       NCHAR (1)      NULL,
    [business_address]   NVARCHAR (128) NULL,
    [business_address2]  NVARCHAR (128) NULL,
    [business_city]      NVARCHAR (32)  NULL,
    [business_state]     NVARCHAR (2)   NULL,
    [business_zip]       NVARCHAR (32)  NULL,
    [business_country]   NVARCHAR (64)  NULL,
    [b_country_code]     NCHAR (2)      NULL,
    [owner_fname]        NVARCHAR (32)  NULL,
    [owner_title]        NVARCHAR (128) NULL,
    [business_phone]     NVARCHAR (32)  NULL,
    [business_fax]       NVARCHAR (32)  NULL,
    [business_url]       NVARCHAR (64)  NULL,
    [owner_email]        NVARCHAR (64)  NULL,
    [c2FirstName]        NVARCHAR (32)  NULL,
    [c2Phone]            NVARCHAR (32)  NULL,
    [c2Fax]              NVARCHAR (32)  NULL,
    [c2Email]            NVARCHAR (64)  NULL,
    [business_fed_taxid] NVARCHAR (16)  NULL,
    [comment]            NVARCHAR (512) NULL,
    [comment2]           NVARCHAR (512) NULL,
    [is_shipper]         NCHAR (1)      NULL,
    [is_agent]           NCHAR (1)      NULL,
    [is_consignee]       NCHAR (1)      NULL,
    [z_is_trucker]       NCHAR (1)      NULL,
    [z_is_special]       NCHAR (1)      NULL,
    [owner_mail_address] NVARCHAR (256) NULL,
    [refferedBy]         NVARCHAR (64)  NULL,
    [date_opened]        DATETIME       NULL,
    [last_update]        DATETIME       NULL
);

