CREATE TABLE [dbo].[users] (
    [elt_account_number]      DECIMAL (8)    NOT NULL,
    [userid]                  DECIMAL (8)    NOT NULL,
    [user_type]               INT            NULL,
    [user_right]              INT            NULL,
    [login_name]              NVARCHAR (100) NOT NULL,
    [password]                NVARCHAR (16)  NULL,
    [org_acct]                DECIMAL (8)    CONSTRAINT [DF_users_org_acct] DEFAULT (0) NULL,
    [user_lname]              NVARCHAR (32)  NULL,
    [user_fname]              NVARCHAR (32)  NULL,
    [user_title]              NVARCHAR (32)  NULL,
    [user_address]            NVARCHAR (64)  NULL,
    [user_city]               NVARCHAR (32)  NULL,
    [user_state]              NVARCHAR (128) NULL,
    [user_zip]                NVARCHAR (32)  NULL,
    [user_country]            NVARCHAR (16)  NULL,
    [user_phone]              NVARCHAR (32)  NULL,
    [user_email]              NVARCHAR (64)  NULL,
    [create_date]             DATETIME       NULL,
    [pw_change_date]          DATETIME       NULL,
    [last_modified]           DATETIME       NULL,
    [last_login_date]         DATETIME       NULL,
    [default_warehouse]       INT            CONSTRAINT [DF_users_default_warehouse] DEFAULT (0) NULL,
    [awb_port]                NVARCHAR (32)  CONSTRAINT [DF_users_awb_port] DEFAULT ('LPT1') NULL,
    [bol_port]                NVARCHAR (32)  CONSTRAINT [DF_users_bol_port] DEFAULT ('LPT1') NULL,
    [sed_port]                NVARCHAR (32)  CONSTRAINT [DF_users_sed_port] DEFAULT ('LPT1') NULL,
    [invoice_port]            NVARCHAR (32)  CONSTRAINT [DF_users_invoice_port] DEFAULT ('LPT1') NULL,
    [check_port]              NVARCHAR (32)  CONSTRAINT [DF_users_check_port] DEFAULT ('LPT1') NULL,
    [shipping_label_port]     NVARCHAR (32)  CONSTRAINT [DF_users_shipping_label_port] DEFAULT ('LPT1') NULL,
    [awb_queue]               NVARCHAR (128) NULL,
    [bol_queue]               NVARCHAR (128) NULL,
    [sed_queue]               NVARCHAR (128) NULL,
    [invoice_queue]           NVARCHAR (128) NULL,
    [check_queue]             NVARCHAR (128) NULL,
    [shipping_label_queue]    NVARCHAR (128) NULL,
    [ig_user_ssn]             NCHAR (9)      NULL,
    [ig_user_dob]             NCHAR (10)     NULL,
    [ig_user_cell]            NVARCHAR (32)  NULL,
    [ig_recent_work]          INT            NULL,
    [page_id]                 INT            NULL,
    [label_type]              DECIMAL (2)    NULL,
    [add_to_label]            NCHAR (1)      NULL,
    [awb_prn_name]            NVARCHAR (64)  NULL,
    [bol_prn_name]            NVARCHAR (64)  NULL,
    [sed_prn_name]            NVARCHAR (64)  NULL,
    [invoice_prn_name]        NVARCHAR (64)  NULL,
    [check_prn_name]          NVARCHAR (64)  NULL,
    [shipping_label_prn_name] NVARCHAR (64)  NULL,
    [is_org_merged]           NCHAR (1)      NULL,
    [page_tab_id]             DECIMAL (18)   NULL,
    CONSTRAINT [PK_users] PRIMARY KEY CLUSTERED ([elt_account_number] ASC, [login_name] ASC)
);

