CREATE TABLE [dbo].[warehouse_receipt] (
    [auto_uid]             DECIMAL (18)    IDENTITY (1, 1) NOT NULL,
    [wr_num]               NVARCHAR (64)   NULL,
    [elt_account_number]   DECIMAL (18)    NULL,
    [carrier_ref_no]       NVARCHAR (64)   NULL,
    [customer_ref_no]      NVARCHAR (64)   NULL,
    [system_date]          DATETIME        CONSTRAINT [DF_warehouse_receipt_system_date] DEFAULT (getdate()) NULL,
    [created_date]         DATETIME        NULL,
    [received_date]        DATETIME        NULL,
    [pickup_date]          DATETIME        NULL,
    [storage_date]         DATETIME        NULL,
    [shipper_acct]         DECIMAL (18)    NULL,
    [shipper_contact]      NVARCHAR (128)  NULL,
    [customer_acct]        DECIMAL (18)    NULL,
    [customer_contact]     NVARCHAR (128)  NULL,
    [trucker_acct]         DECIMAL (18)    NULL,
    [inland_amount]        DECIMAL (16, 2) NULL,
    [inland_type]          NVARCHAR (1)    NULL,
    [danger_good]          NVARCHAR (1)    NULL,
    [handling_info]        NTEXT           NULL,
    [item_piece_origin]    DECIMAL (18)    NULL,
    [item_piece_remain]    DECIMAL (18)    NULL,
    [item_desc]            NTEXT           NULL,
    [item_weight]          DECIMAL (16, 2) NULL,
    [item_weight_scale]    NVARCHAR (3)    NULL,
    [item_dimension]       NVARCHAR (128)  NULL,
    [item_dimension_scale] NVARCHAR (3)    NULL,
    [item_remark]          NTEXT           NULL,
    [job_status]           NVARCHAR (64)   NULL,
    [PO_NO]                NVARCHAR (64)   NULL
);

