CREATE TABLE [dbo].[warehouse_shipout] (
    [auto_uid]             DECIMAL (18)    IDENTITY (1, 1) NOT NULL,
    [so_num]               NVARCHAR (64)   NULL,
    [wr_num]               NVARCHAR (64)   NULL,
    [elt_account_number]   DECIMAL (18)    NULL,
    [carrier_ref_no]       NVARCHAR (64)   NULL,
    [customer_ref_no]      NVARCHAR (64)   NULL,
    [system_date]          DATETIME        CONSTRAINT [DF_warehouse_shipout_system_date] DEFAULT (getdate()) NULL,
    [created_date]         DATETIME        NULL,
    [received_date]        DATETIME        NULL,
    [shipout_date]         DATETIME        NULL,
    [consignee_acct]       DECIMAL (18)    NULL,
    [customer_acct]        DECIMAL (18)    NULL,
    [consignee_contact]    NVARCHAR (128)  NULL,
    [customer_contact]     NVARCHAR (128)  NULL,
    [trucker_acct]         DECIMAL (18)    NULL,
    [inland_amount]        DECIMAL (16, 2) NULL,
    [inland_type]          NVARCHAR (1)    NULL,
    [danger_good]          NVARCHAR (1)    NULL,
    [other_info]           NTEXT           NULL,
    [item_piece_shipout]   DECIMAL (18)    NULL,
    [item_desc]            NTEXT           NULL,
    [item_weight]          DECIMAL (16, 2) NULL,
    [item_weight_scale]    NVARCHAR (3)    NULL,
    [item_dimension]       NVARCHAR (128)  NULL,
    [item_dimension_scale] NVARCHAR (3)    NULL,
    [item_remark]          NTEXT           NULL,
    [shipout_status]       NVARCHAR (32)   NULL,
    [PO_NO]                NVARCHAR (64)   NULL,
    [file_type]            NVARCHAR (2)    NULL,
    [house_num]            NVARCHAR (128)  NULL,
    [master_num]           NVARCHAR (128)  NULL,
    [shipper_info]         NVARCHAR (500)  NULL
);

