								
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','AL ','Alabama')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','AK ','Alaska')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','AZ ','Arizona')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','AR ','Arkansas')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','CA ','California')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','CO ','Colorado')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','CT ','Connecticut')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','DE ','Delaware')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','FL ','Florida')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','GA ','Georgia')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','HI ','Hawaii')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','ID ','Idaho')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','IL ','Illinois')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','IN ','Indiana')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','IA ','Iowa')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','KS ','Kansas')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','KY ','Kentucky')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','LA ','Louisiana')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','ME ','Maine')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','MD ','Maryland')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','MA ','Massachusetts')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','MI ','Michigan')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','MN ','Minnesota')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','MS ','Mississippi')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','MO ','Missouri')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','MT ','Montana')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','NE ','Nebraska')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','NV ','Nevada')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','NH ','New Hampshire')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','NJ ','New Jersey')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','NM ','New Mexico')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','NY ','New York')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','NC ','North Carolina')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','ND ','North Dakota')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','OH ','Ohio')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','OK ','Oklahoma')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','OR ','Oregon')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','PA ','Pennsylvania')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','RI ','Rhode Island')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','SC ','South Carolina')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','SD ','South Dakota')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','TN ','Tennessee')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','TX ','Texas')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','UT ','Utah')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','VT ','Vermont')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','VA ','Virginia')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','WA ','Washington')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','WV ','West Virginia')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','WI ','Wisconsin')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','WY ','Wyoming')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','AS ','American Samoa')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','DC ','District of Columbia')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','FM ','Federated States of Micronesia')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','GU ','Guam')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','MP ','Northern Mariana Islands')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','PW ','Palau')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','PR ','Puerto Rico')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','VI ','Virgin Islands')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','AE ','Armed Forces Africa')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','AA ','Armed Forces Americas')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','AE ','Armed Forces Canada')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','AE ','Armed Forces Europe')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','AE ','Armed Forces Middle East')
INSERT INTO [dbo].[RegionCode]([CountryCode],[Type],[Code] ,[Name]) VALUES('US ','STATE ','AP ','Armed Forces Pacific')

